/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiV1Health200
} from '../model';

import { customInstance } from '../../lib/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Health check endpoint
 */
export type getApiV1HealthResponse200 = {
  data: GetApiV1Health200
  status: 200
}

export type getApiV1HealthResponseSuccess = (getApiV1HealthResponse200) & {
  headers: Headers;
};
;

export type getApiV1HealthResponse = (getApiV1HealthResponseSuccess)

export const getGetApiV1HealthUrl = () => {




  return `/api/v1/health`
}

export const getApiV1Health = async ( options?: RequestInit): Promise<getApiV1HealthResponse> => {

  return customInstance<getApiV1HealthResponse>(getGetApiV1HealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1HealthQueryKey = () => {
    return [
    `/api/v1/health`
    ] as const;
    }


export const getGetApiV1HealthQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Health>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1HealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Health>>> = ({ signal }) => getApiV1Health({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1HealthQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Health>>>
export type GetApiV1HealthQueryError = unknown


/**
 * @summary Health check endpoint
 */

export function useGetApiV1Health<TData = Awaited<ReturnType<typeof getApiV1Health>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1HealthQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






