/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useQueryClient
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetQuizzes200,
  GetQuizzesId200,
  GetQuizzesId404,
  PatchQuizzesQuizIdQuestionsQuestionIdReorder200,
  PatchQuizzesQuizIdQuestionsQuestionIdReorderBody,
  PostQuizzes201,
  PostQuizzes401,
  PostQuizzesBody,
  PostQuizzesQuestionsQuestionIdOptions201,
  PostQuizzesQuestionsQuestionIdOptionsBodyItem,
  PostQuizzesQuizIdQuestions201,
  PostQuizzesQuizIdQuestions401,
  PostQuizzesQuizIdQuestionsBody
} from '../model';

import { apiClient } from '../../lib/api/client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Create a quiz
 */
export const getPostQuizzesUrl = () => {




  return `/api/v1/quizzes`
}

export const postQuizzes = async (postQuizzesBody: PostQuizzesBody, options?: RequestInit): Promise<PostQuizzes201> => {

  return apiClient<PostQuizzes201>(getPostQuizzesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postQuizzesBody,)
  }
);}




export const getPostQuizzesMutationOptions = <TError = PostQuizzes401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postQuizzes>>, TError,{data: PostQuizzesBody}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postQuizzes>>, TError,{data: PostQuizzesBody}, TContext> => {

const mutationKey = ['postQuizzes'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postQuizzes>>, {data: PostQuizzesBody}> = (props) => {
          const {data} = props ?? {};

          return  postQuizzes(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostQuizzesMutationResult = NonNullable<Awaited<ReturnType<typeof postQuizzes>>>
    export type PostQuizzesMutationBody = PostQuizzesBody
    export type PostQuizzesMutationError = PostQuizzes401

    /**
 * @summary Create a quiz
 */
export const usePostQuizzes = <TError = PostQuizzes401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postQuizzes>>, TError,{data: PostQuizzesBody}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postQuizzes>>,
        TError,
        {data: PostQuizzesBody},
        TContext
      > => {
      return useMutation(getPostQuizzesMutationOptions(options), queryClient);
    }
    /**
 * @summary Get all quizzes
 */
export const getGetQuizzesUrl = () => {




  return `/api/v1/quizzes`
}

export const getQuizzes = async ( options?: RequestInit): Promise<GetQuizzes200> => {

  return apiClient<GetQuizzes200>(getGetQuizzesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetQuizzesInfiniteQueryKey = () => {
    return [
    'infinite', `/api/v1/quizzes`
    ] as const;
    }

export const getGetQuizzesQueryKey = () => {
    return [
    `/api/v1/quizzes`
    ] as const;
    }


export const getGetQuizzesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getQuizzes>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getQuizzes>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQuizzesInfiniteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuizzes>>> = ({ signal }) => getQuizzes({ signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 60000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getQuizzes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuizzesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getQuizzes>>>
export type GetQuizzesInfiniteQueryError = unknown


export function useGetQuizzesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getQuizzes>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getQuizzes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuizzes>>,
          TError,
          Awaited<ReturnType<typeof getQuizzes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuizzesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getQuizzes>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getQuizzes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuizzes>>,
          TError,
          Awaited<ReturnType<typeof getQuizzes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuizzesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getQuizzes>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getQuizzes>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all quizzes
 */

export function useGetQuizzesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getQuizzes>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getQuizzes>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQuizzesInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}



/**
 * @summary Get all quizzes
 */
export const useSetGetQuizzesInfiniteQueryData = () => {
  const queryClient = useQueryClient();
  return (updater: InfiniteData<Awaited<ReturnType<typeof getQuizzes>>> | undefined | ((old: InfiniteData<Awaited<ReturnType<typeof getQuizzes>>> | undefined) => InfiniteData<Awaited<ReturnType<typeof getQuizzes>>> | undefined)) => {
    queryClient.setQueryData(getGetQuizzesInfiniteQueryKey(), updater);
  };
}

/**
 * @summary Get all quizzes
 */
export const useGetGetQuizzesInfiniteQueryData = () => {
  const queryClient = useQueryClient();
  return () =>
    queryClient.getQueryData<InfiniteData<Awaited<ReturnType<typeof getQuizzes>>>>(getGetQuizzesInfiniteQueryKey());
}


export const getGetQuizzesQueryOptions = <TData = Awaited<ReturnType<typeof getQuizzes>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizzes>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQuizzesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuizzes>>> = ({ signal }) => getQuizzes({ signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 60000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQuizzes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuizzesQueryResult = NonNullable<Awaited<ReturnType<typeof getQuizzes>>>
export type GetQuizzesQueryError = unknown


export function useGetQuizzes<TData = Awaited<ReturnType<typeof getQuizzes>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizzes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuizzes>>,
          TError,
          Awaited<ReturnType<typeof getQuizzes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuizzes<TData = Awaited<ReturnType<typeof getQuizzes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizzes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuizzes>>,
          TError,
          Awaited<ReturnType<typeof getQuizzes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuizzes<TData = Awaited<ReturnType<typeof getQuizzes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizzes>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all quizzes
 */

export function useGetQuizzes<TData = Awaited<ReturnType<typeof getQuizzes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizzes>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQuizzesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}



/**
 * @summary Get all quizzes
 */
export const useSetGetQuizzesQueryData = () => {
  const queryClient = useQueryClient();
  return (updater: Awaited<ReturnType<typeof getQuizzes>> | undefined | ((old: Awaited<ReturnType<typeof getQuizzes>> | undefined) => Awaited<ReturnType<typeof getQuizzes>> | undefined)) => {
    queryClient.setQueryData(getGetQuizzesQueryKey(), updater);
  };
}

/**
 * @summary Get all quizzes
 */
export const useGetGetQuizzesQueryData = () => {
  const queryClient = useQueryClient();
  return () =>
    queryClient.getQueryData<Awaited<ReturnType<typeof getQuizzes>>>(getGetQuizzesQueryKey());
}


/**
 * @summary Get quiz by id
 */
export const getGetQuizzesIdUrl = (id: string = '123e4567-e89b-12d3-a456-426614174000',) => {




  return `/api/v1/quizzes/${id}`
}

export const getQuizzesId = async (id: string = '123e4567-e89b-12d3-a456-426614174000', options?: RequestInit): Promise<GetQuizzesId200> => {

  return apiClient<GetQuizzesId200>(getGetQuizzesIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetQuizzesIdInfiniteQueryKey = (id: string = '123e4567-e89b-12d3-a456-426614174000',) => {
    return [
    'infinite', `/api/v1/quizzes/${id}`
    ] as const;
    }

export const getGetQuizzesIdQueryKey = (id: string = '123e4567-e89b-12d3-a456-426614174000',) => {
    return [
    `/api/v1/quizzes/${id}`
    ] as const;
    }


export const getGetQuizzesIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getQuizzesId>>>, TError = GetQuizzesId404>(id: string = '123e4567-e89b-12d3-a456-426614174000', options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getQuizzesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQuizzesIdInfiniteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuizzesId>>> = ({ signal }) => getQuizzesId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id),  staleTime: 60000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getQuizzesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuizzesIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getQuizzesId>>>
export type GetQuizzesIdInfiniteQueryError = GetQuizzesId404


export function useGetQuizzesIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getQuizzesId>>>, TError = GetQuizzesId404>(
 id: undefined |  string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getQuizzesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuizzesId>>,
          TError,
          Awaited<ReturnType<typeof getQuizzesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuizzesIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getQuizzesId>>>, TError = GetQuizzesId404>(
 id?: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getQuizzesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuizzesId>>,
          TError,
          Awaited<ReturnType<typeof getQuizzesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuizzesIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getQuizzesId>>>, TError = GetQuizzesId404>(
 id?: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getQuizzesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get quiz by id
 */

export function useGetQuizzesIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getQuizzesId>>>, TError = GetQuizzesId404>(
 id: string = '123e4567-e89b-12d3-a456-426614174000', options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getQuizzesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQuizzesIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}



/**
 * @summary Get quiz by id
 */
export const useSetGetQuizzesIdInfiniteQueryData = () => {
  const queryClient = useQueryClient();
  return (id: string = '123e4567-e89b-12d3-a456-426614174000',updater: InfiniteData<Awaited<ReturnType<typeof getQuizzesId>>> | undefined | ((old: InfiniteData<Awaited<ReturnType<typeof getQuizzesId>>> | undefined) => InfiniteData<Awaited<ReturnType<typeof getQuizzesId>>> | undefined)) => {
    queryClient.setQueryData(getGetQuizzesIdInfiniteQueryKey(id), updater);
  };
}

/**
 * @summary Get quiz by id
 */
export const useGetGetQuizzesIdInfiniteQueryData = () => {
  const queryClient = useQueryClient();
  return (id: string = '123e4567-e89b-12d3-a456-426614174000',) =>
    queryClient.getQueryData<InfiniteData<Awaited<ReturnType<typeof getQuizzesId>>>>(getGetQuizzesIdInfiniteQueryKey(id));
}


export const getGetQuizzesIdQueryOptions = <TData = Awaited<ReturnType<typeof getQuizzesId>>, TError = GetQuizzesId404>(id: string = '123e4567-e89b-12d3-a456-426614174000', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizzesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQuizzesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuizzesId>>> = ({ signal }) => getQuizzesId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id),  staleTime: 60000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQuizzesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuizzesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getQuizzesId>>>
export type GetQuizzesIdQueryError = GetQuizzesId404


export function useGetQuizzesId<TData = Awaited<ReturnType<typeof getQuizzesId>>, TError = GetQuizzesId404>(
 id: undefined |  string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizzesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuizzesId>>,
          TError,
          Awaited<ReturnType<typeof getQuizzesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuizzesId<TData = Awaited<ReturnType<typeof getQuizzesId>>, TError = GetQuizzesId404>(
 id?: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizzesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuizzesId>>,
          TError,
          Awaited<ReturnType<typeof getQuizzesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuizzesId<TData = Awaited<ReturnType<typeof getQuizzesId>>, TError = GetQuizzesId404>(
 id?: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizzesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get quiz by id
 */

export function useGetQuizzesId<TData = Awaited<ReturnType<typeof getQuizzesId>>, TError = GetQuizzesId404>(
 id: string = '123e4567-e89b-12d3-a456-426614174000', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizzesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQuizzesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}



/**
 * @summary Get quiz by id
 */
export const useSetGetQuizzesIdQueryData = () => {
  const queryClient = useQueryClient();
  return (id: string = '123e4567-e89b-12d3-a456-426614174000',updater: Awaited<ReturnType<typeof getQuizzesId>> | undefined | ((old: Awaited<ReturnType<typeof getQuizzesId>> | undefined) => Awaited<ReturnType<typeof getQuizzesId>> | undefined)) => {
    queryClient.setQueryData(getGetQuizzesIdQueryKey(id), updater);
  };
}

/**
 * @summary Get quiz by id
 */
export const useGetGetQuizzesIdQueryData = () => {
  const queryClient = useQueryClient();
  return (id: string = '123e4567-e89b-12d3-a456-426614174000',) =>
    queryClient.getQueryData<Awaited<ReturnType<typeof getQuizzesId>>>(getGetQuizzesIdQueryKey(id));
}


/**
 * @summary Add question to quiz
 */
export const getPostQuizzesQuizIdQuestionsUrl = (quizId: string = '123e4567-e89b-12d3-a456-426614174000',) => {




  return `/api/v1/quizzes/${quizId}/questions`
}

export const postQuizzesQuizIdQuestions = async (postQuizzesQuizIdQuestionsBody: PostQuizzesQuizIdQuestionsBody,
    quizId: string = '123e4567-e89b-12d3-a456-426614174000', options?: RequestInit): Promise<PostQuizzesQuizIdQuestions201> => {

  return apiClient<PostQuizzesQuizIdQuestions201>(getPostQuizzesQuizIdQuestionsUrl(quizId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postQuizzesQuizIdQuestionsBody,)
  }
);}




export const getPostQuizzesQuizIdQuestionsMutationOptions = <TError = PostQuizzesQuizIdQuestions401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postQuizzesQuizIdQuestions>>, TError,{data: PostQuizzesQuizIdQuestionsBody;quizId?: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postQuizzesQuizIdQuestions>>, TError,{data: PostQuizzesQuizIdQuestionsBody;quizId?: string}, TContext> => {

const mutationKey = ['postQuizzesQuizIdQuestions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postQuizzesQuizIdQuestions>>, {data: PostQuizzesQuizIdQuestionsBody;quizId?: string}> = (props) => {
          const {data,quizId} = props ?? {};

          return  postQuizzesQuizIdQuestions(data,quizId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostQuizzesQuizIdQuestionsMutationResult = NonNullable<Awaited<ReturnType<typeof postQuizzesQuizIdQuestions>>>
    export type PostQuizzesQuizIdQuestionsMutationBody = PostQuizzesQuizIdQuestionsBody
    export type PostQuizzesQuizIdQuestionsMutationError = PostQuizzesQuizIdQuestions401

    /**
 * @summary Add question to quiz
 */
export const usePostQuizzesQuizIdQuestions = <TError = PostQuizzesQuizIdQuestions401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postQuizzesQuizIdQuestions>>, TError,{data: PostQuizzesQuizIdQuestionsBody;quizId?: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postQuizzesQuizIdQuestions>>,
        TError,
        {data: PostQuizzesQuizIdQuestionsBody;quizId?: string},
        TContext
      > => {
      return useMutation(getPostQuizzesQuizIdQuestionsMutationOptions(options), queryClient);
    }
    /**
 * @summary Add options to question
 */
export const getPostQuizzesQuestionsQuestionIdOptionsUrl = (questionId: string = '123e4567-e89b-12d3-a456-426614174000',) => {




  return `/api/v1/quizzes/questions/${questionId}/options`
}

export const postQuizzesQuestionsQuestionIdOptions = async (postQuizzesQuestionsQuestionIdOptionsBodyItem: PostQuizzesQuestionsQuestionIdOptionsBodyItem[],
    questionId: string = '123e4567-e89b-12d3-a456-426614174000', options?: RequestInit): Promise<PostQuizzesQuestionsQuestionIdOptions201> => {

  return apiClient<PostQuizzesQuestionsQuestionIdOptions201>(getPostQuizzesQuestionsQuestionIdOptionsUrl(questionId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postQuizzesQuestionsQuestionIdOptionsBodyItem,)
  }
);}




export const getPostQuizzesQuestionsQuestionIdOptionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postQuizzesQuestionsQuestionIdOptions>>, TError,{data: PostQuizzesQuestionsQuestionIdOptionsBodyItem[];questionId?: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postQuizzesQuestionsQuestionIdOptions>>, TError,{data: PostQuizzesQuestionsQuestionIdOptionsBodyItem[];questionId?: string}, TContext> => {

const mutationKey = ['postQuizzesQuestionsQuestionIdOptions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postQuizzesQuestionsQuestionIdOptions>>, {data: PostQuizzesQuestionsQuestionIdOptionsBodyItem[];questionId?: string}> = (props) => {
          const {data,questionId} = props ?? {};

          return  postQuizzesQuestionsQuestionIdOptions(data,questionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostQuizzesQuestionsQuestionIdOptionsMutationResult = NonNullable<Awaited<ReturnType<typeof postQuizzesQuestionsQuestionIdOptions>>>
    export type PostQuizzesQuestionsQuestionIdOptionsMutationBody = PostQuizzesQuestionsQuestionIdOptionsBodyItem[]
    export type PostQuizzesQuestionsQuestionIdOptionsMutationError = unknown

    /**
 * @summary Add options to question
 */
export const usePostQuizzesQuestionsQuestionIdOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postQuizzesQuestionsQuestionIdOptions>>, TError,{data: PostQuizzesQuestionsQuestionIdOptionsBodyItem[];questionId?: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postQuizzesQuestionsQuestionIdOptions>>,
        TError,
        {data: PostQuizzesQuestionsQuestionIdOptionsBodyItem[];questionId?: string},
        TContext
      > => {
      return useMutation(getPostQuizzesQuestionsQuestionIdOptionsMutationOptions(options), queryClient);
    }
    /**
 * @summary Reorder a question inside a quiz
 */
export const getPatchQuizzesQuizIdQuestionsQuestionIdReorderUrl = (quizId: string = '123e4567-e89b-12d3-a456-426614174000',
    questionId: string = '123e4567-e89b-12d3-a456-426614174000',) => {




  return `/api/v1/quizzes/${quizId}/questions/${questionId}/reorder`
}

export const patchQuizzesQuizIdQuestionsQuestionIdReorder = async (patchQuizzesQuizIdQuestionsQuestionIdReorderBody: PatchQuizzesQuizIdQuestionsQuestionIdReorderBody,
    quizId: string = '123e4567-e89b-12d3-a456-426614174000',
    questionId: string = '123e4567-e89b-12d3-a456-426614174000', options?: RequestInit): Promise<PatchQuizzesQuizIdQuestionsQuestionIdReorder200> => {

  return apiClient<PatchQuizzesQuizIdQuestionsQuestionIdReorder200>(getPatchQuizzesQuizIdQuestionsQuestionIdReorderUrl(quizId,questionId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchQuizzesQuizIdQuestionsQuestionIdReorderBody,)
  }
);}




export const getPatchQuizzesQuizIdQuestionsQuestionIdReorderMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchQuizzesQuizIdQuestionsQuestionIdReorder>>, TError,{data: PatchQuizzesQuizIdQuestionsQuestionIdReorderBody;quizId?: string;questionId?: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof patchQuizzesQuizIdQuestionsQuestionIdReorder>>, TError,{data: PatchQuizzesQuizIdQuestionsQuestionIdReorderBody;quizId?: string;questionId?: string}, TContext> => {

const mutationKey = ['patchQuizzesQuizIdQuestionsQuestionIdReorder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchQuizzesQuizIdQuestionsQuestionIdReorder>>, {data: PatchQuizzesQuizIdQuestionsQuestionIdReorderBody;quizId?: string;questionId?: string}> = (props) => {
          const {data,quizId,questionId} = props ?? {};

          return  patchQuizzesQuizIdQuestionsQuestionIdReorder(data,quizId,questionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchQuizzesQuizIdQuestionsQuestionIdReorderMutationResult = NonNullable<Awaited<ReturnType<typeof patchQuizzesQuizIdQuestionsQuestionIdReorder>>>
    export type PatchQuizzesQuizIdQuestionsQuestionIdReorderMutationBody = PatchQuizzesQuizIdQuestionsQuestionIdReorderBody
    export type PatchQuizzesQuizIdQuestionsQuestionIdReorderMutationError = unknown

    /**
 * @summary Reorder a question inside a quiz
 */
export const usePatchQuizzesQuizIdQuestionsQuestionIdReorder = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchQuizzesQuizIdQuestionsQuestionIdReorder>>, TError,{data: PatchQuizzesQuizIdQuestionsQuestionIdReorderBody;quizId?: string;questionId?: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchQuizzesQuizIdQuestionsQuestionIdReorder>>,
        TError,
        {data: PatchQuizzesQuizIdQuestionsQuestionIdReorderBody;quizId?: string;questionId?: string},
        TContext
      > => {
      return useMutation(getPatchQuizzesQuizIdQuestionsQuestionIdReorderMutationOptions(options), queryClient);
    }
