/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiV1Quizzes200,
  GetApiV1QuizzesId200,
  GetApiV1QuizzesId404,
  PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorder200,
  PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorderBody,
  PostApiV1Quizzes201,
  PostApiV1Quizzes401,
  PostApiV1QuizzesBody,
  PostApiV1QuizzesQuestionsQuestionIdOptions201,
  PostApiV1QuizzesQuestionsQuestionIdOptionsBodyItem,
  PostApiV1QuizzesQuizIdQuestions201,
  PostApiV1QuizzesQuizIdQuestions401,
  PostApiV1QuizzesQuizIdQuestionsBody
} from '../model';

import { customInstance } from '../../lib/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Create a quiz
 */
export type postApiV1QuizzesResponse201 = {
  data: PostApiV1Quizzes201
  status: 201
}

export type postApiV1QuizzesResponse401 = {
  data: PostApiV1Quizzes401
  status: 401
}

export type postApiV1QuizzesResponseSuccess = (postApiV1QuizzesResponse201) & {
  headers: Headers;
};
export type postApiV1QuizzesResponseError = (postApiV1QuizzesResponse401) & {
  headers: Headers;
};

export type postApiV1QuizzesResponse = (postApiV1QuizzesResponseSuccess | postApiV1QuizzesResponseError)

export const getPostApiV1QuizzesUrl = () => {




  return `/api/v1/quizzes`
}

export const postApiV1Quizzes = async (postApiV1QuizzesBody: PostApiV1QuizzesBody, options?: RequestInit): Promise<postApiV1QuizzesResponse> => {

  return customInstance<postApiV1QuizzesResponse>(getPostApiV1QuizzesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1QuizzesBody,)
  }
);}




export const getPostApiV1QuizzesMutationOptions = <TError = PostApiV1Quizzes401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Quizzes>>, TError,{data: PostApiV1QuizzesBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Quizzes>>, TError,{data: PostApiV1QuizzesBody}, TContext> => {

const mutationKey = ['postApiV1Quizzes'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Quizzes>>, {data: PostApiV1QuizzesBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Quizzes(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1QuizzesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Quizzes>>>
    export type PostApiV1QuizzesMutationBody = PostApiV1QuizzesBody
    export type PostApiV1QuizzesMutationError = PostApiV1Quizzes401

    /**
 * @summary Create a quiz
 */
export const usePostApiV1Quizzes = <TError = PostApiV1Quizzes401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Quizzes>>, TError,{data: PostApiV1QuizzesBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Quizzes>>,
        TError,
        {data: PostApiV1QuizzesBody},
        TContext
      > => {
      return useMutation(getPostApiV1QuizzesMutationOptions(options), queryClient);
    }
    /**
 * @summary Get all quizzes
 */
export type getApiV1QuizzesResponse200 = {
  data: GetApiV1Quizzes200
  status: 200
}

export type getApiV1QuizzesResponseSuccess = (getApiV1QuizzesResponse200) & {
  headers: Headers;
};
;

export type getApiV1QuizzesResponse = (getApiV1QuizzesResponseSuccess)

export const getGetApiV1QuizzesUrl = () => {




  return `/api/v1/quizzes`
}

export const getApiV1Quizzes = async ( options?: RequestInit): Promise<getApiV1QuizzesResponse> => {

  return customInstance<getApiV1QuizzesResponse>(getGetApiV1QuizzesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1QuizzesQueryKey = () => {
    return [
    `/api/v1/quizzes`
    ] as const;
    }


export const getGetApiV1QuizzesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Quizzes>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Quizzes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1QuizzesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Quizzes>>> = ({ signal }) => getApiV1Quizzes({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Quizzes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1QuizzesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Quizzes>>>
export type GetApiV1QuizzesQueryError = unknown


export function useGetApiV1Quizzes<TData = Awaited<ReturnType<typeof getApiV1Quizzes>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Quizzes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Quizzes>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Quizzes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Quizzes<TData = Awaited<ReturnType<typeof getApiV1Quizzes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Quizzes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Quizzes>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Quizzes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Quizzes<TData = Awaited<ReturnType<typeof getApiV1Quizzes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Quizzes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all quizzes
 */

export function useGetApiV1Quizzes<TData = Awaited<ReturnType<typeof getApiV1Quizzes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Quizzes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1QuizzesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Get quiz by id
 */
export type getApiV1QuizzesIdResponse200 = {
  data: GetApiV1QuizzesId200
  status: 200
}

export type getApiV1QuizzesIdResponse404 = {
  data: GetApiV1QuizzesId404
  status: 404
}

export type getApiV1QuizzesIdResponseSuccess = (getApiV1QuizzesIdResponse200) & {
  headers: Headers;
};
export type getApiV1QuizzesIdResponseError = (getApiV1QuizzesIdResponse404) & {
  headers: Headers;
};

export type getApiV1QuizzesIdResponse = (getApiV1QuizzesIdResponseSuccess | getApiV1QuizzesIdResponseError)

export const getGetApiV1QuizzesIdUrl = (id: string,) => {




  return `/api/v1/quizzes/${id}`
}

export const getApiV1QuizzesId = async (id: string, options?: RequestInit): Promise<getApiV1QuizzesIdResponse> => {

  return customInstance<getApiV1QuizzesIdResponse>(getGetApiV1QuizzesIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1QuizzesIdQueryKey = (id: string,) => {
    return [
    `/api/v1/quizzes/${id}`
    ] as const;
    }


export const getGetApiV1QuizzesIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1QuizzesId>>, TError = GetApiV1QuizzesId404>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1QuizzesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1QuizzesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1QuizzesId>>> = ({ signal }) => getApiV1QuizzesId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1QuizzesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1QuizzesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1QuizzesId>>>
export type GetApiV1QuizzesIdQueryError = GetApiV1QuizzesId404


export function useGetApiV1QuizzesId<TData = Awaited<ReturnType<typeof getApiV1QuizzesId>>, TError = GetApiV1QuizzesId404>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1QuizzesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1QuizzesId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1QuizzesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1QuizzesId<TData = Awaited<ReturnType<typeof getApiV1QuizzesId>>, TError = GetApiV1QuizzesId404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1QuizzesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1QuizzesId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1QuizzesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1QuizzesId<TData = Awaited<ReturnType<typeof getApiV1QuizzesId>>, TError = GetApiV1QuizzesId404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1QuizzesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get quiz by id
 */

export function useGetApiV1QuizzesId<TData = Awaited<ReturnType<typeof getApiV1QuizzesId>>, TError = GetApiV1QuizzesId404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1QuizzesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1QuizzesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Add question to quiz
 */
export type postApiV1QuizzesQuizIdQuestionsResponse201 = {
  data: PostApiV1QuizzesQuizIdQuestions201
  status: 201
}

export type postApiV1QuizzesQuizIdQuestionsResponse401 = {
  data: PostApiV1QuizzesQuizIdQuestions401
  status: 401
}

export type postApiV1QuizzesQuizIdQuestionsResponseSuccess = (postApiV1QuizzesQuizIdQuestionsResponse201) & {
  headers: Headers;
};
export type postApiV1QuizzesQuizIdQuestionsResponseError = (postApiV1QuizzesQuizIdQuestionsResponse401) & {
  headers: Headers;
};

export type postApiV1QuizzesQuizIdQuestionsResponse = (postApiV1QuizzesQuizIdQuestionsResponseSuccess | postApiV1QuizzesQuizIdQuestionsResponseError)

export const getPostApiV1QuizzesQuizIdQuestionsUrl = (quizId: string,) => {




  return `/api/v1/quizzes/${quizId}/questions`
}

export const postApiV1QuizzesQuizIdQuestions = async (quizId: string,
    postApiV1QuizzesQuizIdQuestionsBody: PostApiV1QuizzesQuizIdQuestionsBody, options?: RequestInit): Promise<postApiV1QuizzesQuizIdQuestionsResponse> => {

  return customInstance<postApiV1QuizzesQuizIdQuestionsResponse>(getPostApiV1QuizzesQuizIdQuestionsUrl(quizId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1QuizzesQuizIdQuestionsBody,)
  }
);}




export const getPostApiV1QuizzesQuizIdQuestionsMutationOptions = <TError = PostApiV1QuizzesQuizIdQuestions401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuizzesQuizIdQuestions>>, TError,{quizId: string;data: PostApiV1QuizzesQuizIdQuestionsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuizzesQuizIdQuestions>>, TError,{quizId: string;data: PostApiV1QuizzesQuizIdQuestionsBody}, TContext> => {

const mutationKey = ['postApiV1QuizzesQuizIdQuestions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1QuizzesQuizIdQuestions>>, {quizId: string;data: PostApiV1QuizzesQuizIdQuestionsBody}> = (props) => {
          const {quizId,data} = props ?? {};

          return  postApiV1QuizzesQuizIdQuestions(quizId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1QuizzesQuizIdQuestionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1QuizzesQuizIdQuestions>>>
    export type PostApiV1QuizzesQuizIdQuestionsMutationBody = PostApiV1QuizzesQuizIdQuestionsBody
    export type PostApiV1QuizzesQuizIdQuestionsMutationError = PostApiV1QuizzesQuizIdQuestions401

    /**
 * @summary Add question to quiz
 */
export const usePostApiV1QuizzesQuizIdQuestions = <TError = PostApiV1QuizzesQuizIdQuestions401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuizzesQuizIdQuestions>>, TError,{quizId: string;data: PostApiV1QuizzesQuizIdQuestionsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1QuizzesQuizIdQuestions>>,
        TError,
        {quizId: string;data: PostApiV1QuizzesQuizIdQuestionsBody},
        TContext
      > => {
      return useMutation(getPostApiV1QuizzesQuizIdQuestionsMutationOptions(options), queryClient);
    }
    /**
 * @summary Add options to question
 */
export type postApiV1QuizzesQuestionsQuestionIdOptionsResponse201 = {
  data: PostApiV1QuizzesQuestionsQuestionIdOptions201
  status: 201
}

export type postApiV1QuizzesQuestionsQuestionIdOptionsResponseSuccess = (postApiV1QuizzesQuestionsQuestionIdOptionsResponse201) & {
  headers: Headers;
};
;

export type postApiV1QuizzesQuestionsQuestionIdOptionsResponse = (postApiV1QuizzesQuestionsQuestionIdOptionsResponseSuccess)

export const getPostApiV1QuizzesQuestionsQuestionIdOptionsUrl = (questionId: string,) => {




  return `/api/v1/quizzes/questions/${questionId}/options`
}

export const postApiV1QuizzesQuestionsQuestionIdOptions = async (questionId: string,
    postApiV1QuizzesQuestionsQuestionIdOptionsBodyItem: PostApiV1QuizzesQuestionsQuestionIdOptionsBodyItem[], options?: RequestInit): Promise<postApiV1QuizzesQuestionsQuestionIdOptionsResponse> => {

  return customInstance<postApiV1QuizzesQuestionsQuestionIdOptionsResponse>(getPostApiV1QuizzesQuestionsQuestionIdOptionsUrl(questionId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1QuizzesQuestionsQuestionIdOptionsBodyItem,)
  }
);}




export const getPostApiV1QuizzesQuestionsQuestionIdOptionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuizzesQuestionsQuestionIdOptions>>, TError,{questionId: string;data: PostApiV1QuizzesQuestionsQuestionIdOptionsBodyItem[]}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuizzesQuestionsQuestionIdOptions>>, TError,{questionId: string;data: PostApiV1QuizzesQuestionsQuestionIdOptionsBodyItem[]}, TContext> => {

const mutationKey = ['postApiV1QuizzesQuestionsQuestionIdOptions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1QuizzesQuestionsQuestionIdOptions>>, {questionId: string;data: PostApiV1QuizzesQuestionsQuestionIdOptionsBodyItem[]}> = (props) => {
          const {questionId,data} = props ?? {};

          return  postApiV1QuizzesQuestionsQuestionIdOptions(questionId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1QuizzesQuestionsQuestionIdOptionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1QuizzesQuestionsQuestionIdOptions>>>
    export type PostApiV1QuizzesQuestionsQuestionIdOptionsMutationBody = PostApiV1QuizzesQuestionsQuestionIdOptionsBodyItem[]
    export type PostApiV1QuizzesQuestionsQuestionIdOptionsMutationError = unknown

    /**
 * @summary Add options to question
 */
export const usePostApiV1QuizzesQuestionsQuestionIdOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuizzesQuestionsQuestionIdOptions>>, TError,{questionId: string;data: PostApiV1QuizzesQuestionsQuestionIdOptionsBodyItem[]}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1QuizzesQuestionsQuestionIdOptions>>,
        TError,
        {questionId: string;data: PostApiV1QuizzesQuestionsQuestionIdOptionsBodyItem[]},
        TContext
      > => {
      return useMutation(getPostApiV1QuizzesQuestionsQuestionIdOptionsMutationOptions(options), queryClient);
    }
    /**
 * @summary Reorder a question inside a quiz
 */
export type patchApiV1QuizzesQuizIdQuestionsQuestionIdReorderResponse200 = {
  data: PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorder200
  status: 200
}

export type patchApiV1QuizzesQuizIdQuestionsQuestionIdReorderResponseSuccess = (patchApiV1QuizzesQuizIdQuestionsQuestionIdReorderResponse200) & {
  headers: Headers;
};
;

export type patchApiV1QuizzesQuizIdQuestionsQuestionIdReorderResponse = (patchApiV1QuizzesQuizIdQuestionsQuestionIdReorderResponseSuccess)

export const getPatchApiV1QuizzesQuizIdQuestionsQuestionIdReorderUrl = (quizId: string,
    questionId: string,) => {




  return `/api/v1/quizzes/${quizId}/questions/${questionId}/reorder`
}

export const patchApiV1QuizzesQuizIdQuestionsQuestionIdReorder = async (quizId: string,
    questionId: string,
    patchApiV1QuizzesQuizIdQuestionsQuestionIdReorderBody: PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorderBody, options?: RequestInit): Promise<patchApiV1QuizzesQuizIdQuestionsQuestionIdReorderResponse> => {

  return customInstance<patchApiV1QuizzesQuizIdQuestionsQuestionIdReorderResponse>(getPatchApiV1QuizzesQuizIdQuestionsQuestionIdReorderUrl(quizId,questionId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchApiV1QuizzesQuizIdQuestionsQuestionIdReorderBody,)
  }
);}




export const getPatchApiV1QuizzesQuizIdQuestionsQuestionIdReorderMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1QuizzesQuizIdQuestionsQuestionIdReorder>>, TError,{quizId: string;questionId: string;data: PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorderBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1QuizzesQuizIdQuestionsQuestionIdReorder>>, TError,{quizId: string;questionId: string;data: PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorderBody}, TContext> => {

const mutationKey = ['patchApiV1QuizzesQuizIdQuestionsQuestionIdReorder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1QuizzesQuizIdQuestionsQuestionIdReorder>>, {quizId: string;questionId: string;data: PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorderBody}> = (props) => {
          const {quizId,questionId,data} = props ?? {};

          return  patchApiV1QuizzesQuizIdQuestionsQuestionIdReorder(quizId,questionId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorderMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1QuizzesQuizIdQuestionsQuestionIdReorder>>>
    export type PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorderMutationBody = PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorderBody
    export type PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorderMutationError = unknown

    /**
 * @summary Reorder a question inside a quiz
 */
export const usePatchApiV1QuizzesQuizIdQuestionsQuestionIdReorder = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1QuizzesQuizIdQuestionsQuestionIdReorder>>, TError,{quizId: string;questionId: string;data: PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorderBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1QuizzesQuizIdQuestionsQuestionIdReorder>>,
        TError,
        {quizId: string;questionId: string;data: PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorderBody},
        TContext
      > => {
      return useMutation(getPatchApiV1QuizzesQuizIdQuestionsQuestionIdReorderMutationOptions(options), queryClient);
    }
