/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiV1AuthMe200,
  GetApiV1AuthMe401,
  PostApiV1AuthLogin200,
  PostApiV1AuthLogin401,
  PostApiV1AuthLoginBody,
  PostApiV1AuthRegister201,
  PostApiV1AuthRegister409,
  PostApiV1AuthRegisterBody
} from '../model';

import { customInstance } from '../../lib/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Register a new user
 */
export type postApiV1AuthRegisterResponse201 = {
  data: PostApiV1AuthRegister201
  status: 201
}

export type postApiV1AuthRegisterResponse409 = {
  data: PostApiV1AuthRegister409
  status: 409
}

export type postApiV1AuthRegisterResponseSuccess = (postApiV1AuthRegisterResponse201) & {
  headers: Headers;
};
export type postApiV1AuthRegisterResponseError = (postApiV1AuthRegisterResponse409) & {
  headers: Headers;
};

export type postApiV1AuthRegisterResponse = (postApiV1AuthRegisterResponseSuccess | postApiV1AuthRegisterResponseError)

export const getPostApiV1AuthRegisterUrl = () => {




  return `/api/v1/auth/register`
}

export const postApiV1AuthRegister = async (postApiV1AuthRegisterBody: PostApiV1AuthRegisterBody, options?: RequestInit): Promise<postApiV1AuthRegisterResponse> => {

  return customInstance<postApiV1AuthRegisterResponse>(getPostApiV1AuthRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1AuthRegisterBody,)
  }
);}




export const getPostApiV1AuthRegisterMutationOptions = <TError = PostApiV1AuthRegister409,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthRegister>>, TError,{data: PostApiV1AuthRegisterBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthRegister>>, TError,{data: PostApiV1AuthRegisterBody}, TContext> => {

const mutationKey = ['postApiV1AuthRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthRegister>>, {data: PostApiV1AuthRegisterBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthRegister(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthRegister>>>
    export type PostApiV1AuthRegisterMutationBody = PostApiV1AuthRegisterBody
    export type PostApiV1AuthRegisterMutationError = PostApiV1AuthRegister409

    /**
 * @summary Register a new user
 */
export const usePostApiV1AuthRegister = <TError = PostApiV1AuthRegister409,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthRegister>>, TError,{data: PostApiV1AuthRegisterBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthRegister>>,
        TError,
        {data: PostApiV1AuthRegisterBody},
        TContext
      > => {
      return useMutation(getPostApiV1AuthRegisterMutationOptions(options));
    }
    /**
 * @summary Authenticate a user
 */
export type postApiV1AuthLoginResponse200 = {
  data: PostApiV1AuthLogin200
  status: 200
}

export type postApiV1AuthLoginResponse401 = {
  data: PostApiV1AuthLogin401
  status: 401
}

export type postApiV1AuthLoginResponseSuccess = (postApiV1AuthLoginResponse200) & {
  headers: Headers;
};
export type postApiV1AuthLoginResponseError = (postApiV1AuthLoginResponse401) & {
  headers: Headers;
};

export type postApiV1AuthLoginResponse = (postApiV1AuthLoginResponseSuccess | postApiV1AuthLoginResponseError)

export const getPostApiV1AuthLoginUrl = () => {




  return `/api/v1/auth/login`
}

export const postApiV1AuthLogin = async (postApiV1AuthLoginBody: PostApiV1AuthLoginBody, options?: RequestInit): Promise<postApiV1AuthLoginResponse> => {

  return customInstance<postApiV1AuthLoginResponse>(getPostApiV1AuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1AuthLoginBody,)
  }
);}




export const getPostApiV1AuthLoginMutationOptions = <TError = PostApiV1AuthLogin401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogin>>, TError,{data: PostApiV1AuthLoginBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogin>>, TError,{data: PostApiV1AuthLoginBody}, TContext> => {

const mutationKey = ['postApiV1AuthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthLogin>>, {data: PostApiV1AuthLoginBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthLogin>>>
    export type PostApiV1AuthLoginMutationBody = PostApiV1AuthLoginBody
    export type PostApiV1AuthLoginMutationError = PostApiV1AuthLogin401

    /**
 * @summary Authenticate a user
 */
export const usePostApiV1AuthLogin = <TError = PostApiV1AuthLogin401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogin>>, TError,{data: PostApiV1AuthLoginBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthLogin>>,
        TError,
        {data: PostApiV1AuthLoginBody},
        TContext
      > => {
      return useMutation(getPostApiV1AuthLoginMutationOptions(options));
    }
    /**
 * @summary Get current authenticated user
 */
export type getApiV1AuthMeResponse200 = {
  data: GetApiV1AuthMe200
  status: 200
}

export type getApiV1AuthMeResponse401 = {
  data: GetApiV1AuthMe401
  status: 401
}

export type getApiV1AuthMeResponseSuccess = (getApiV1AuthMeResponse200) & {
  headers: Headers;
};
export type getApiV1AuthMeResponseError = (getApiV1AuthMeResponse401) & {
  headers: Headers;
};

export type getApiV1AuthMeResponse = (getApiV1AuthMeResponseSuccess | getApiV1AuthMeResponseError)

export const getGetApiV1AuthMeUrl = () => {




  return `/api/v1/auth/me`
}

export const getApiV1AuthMe = async ( options?: RequestInit): Promise<getApiV1AuthMeResponse> => {

  return customInstance<getApiV1AuthMeResponse>(getGetApiV1AuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AuthMeQueryKey = () => {
    return [
    `/api/v1/auth/me`
    ] as const;
    }


export const getGetApiV1AuthMeQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AuthMe>>, TError = GetApiV1AuthMe401>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthMe>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AuthMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AuthMe>>> = ({ signal }) => getApiV1AuthMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthMe>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1AuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AuthMe>>>
export type GetApiV1AuthMeQueryError = GetApiV1AuthMe401


/**
 * @summary Get current authenticated user
 */

export function useGetApiV1AuthMe<TData = Awaited<ReturnType<typeof getApiV1AuthMe>>, TError = GetApiV1AuthMe401>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthMe>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1AuthMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






