/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useQueryClient,
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetUsersId200,
  GetUsersId401,
  GetUsersId403,
  GetUsersId404,
  GetUsersId500,
  PostUsers201,
  PostUsers400,
  PostUsers409,
  PostUsers500,
  PostUsersBody,
} from '../model';

import { apiClient } from '../../lib/api/client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create user
 */
export const getPostUsersUrl = () => {
  return `/api/v1/users`;
};

export const postUsers = async (
  postUsersBody: PostUsersBody,
  options?: RequestInit
): Promise<PostUsers201> => {
  return apiClient<PostUsers201>(getPostUsersUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postUsersBody),
  });
};

export const getPostUsersMutationOptions = <
  TError = PostUsers400 | PostUsers409 | PostUsers500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postUsers>>,
    TError,
    { data: PostUsersBody },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postUsers>>,
  TError,
  { data: PostUsersBody },
  TContext
> => {
  const mutationKey = ['postUsers'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postUsers>>,
    { data: PostUsersBody }
  > = props => {
    const { data } = props ?? {};

    return postUsers(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostUsersMutationResult = NonNullable<
  Awaited<ReturnType<typeof postUsers>>
>;
export type PostUsersMutationBody = PostUsersBody;
export type PostUsersMutationError = PostUsers400 | PostUsers409 | PostUsers500;

/**
 * @summary Create user
 */
export const usePostUsers = <
  TError = PostUsers400 | PostUsers409 | PostUsers500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postUsers>>,
      TError,
      { data: PostUsersBody },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postUsers>>,
  TError,
  { data: PostUsersBody },
  TContext
> => {
  return useMutation(getPostUsersMutationOptions(options), queryClient);
};
/**
 * @summary Get user by id
 */
export const getGetUsersIdUrl = (id: string) => {
  return `/api/v1/users/${id}`;
};

export const getUsersId = async (
  id: string,
  options?: RequestInit
): Promise<GetUsersId200> => {
  return apiClient<GetUsersId200>(getGetUsersIdUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getGetUsersIdInfiniteQueryKey = (id: string) => {
  return ['infinite', `/api/v1/users/${id}`] as const;
};

export const getGetUsersIdQueryKey = (id: string) => {
  return [`/api/v1/users/${id}`] as const;
};

export const getGetUsersIdInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getUsersId>>>,
  TError = GetUsersId401 | GetUsersId403 | GetUsersId404 | GetUsersId500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getUsersId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUsersIdInfiniteQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersId>>> = ({
    signal,
  }) => getUsersId(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 60000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getUsersId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersIdInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsersId>>
>;
export type GetUsersIdInfiniteQueryError =
  | GetUsersId401
  | GetUsersId403
  | GetUsersId404
  | GetUsersId500;

export function useGetUsersIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getUsersId>>>,
  TError = GetUsersId401 | GetUsersId403 | GetUsersId404 | GetUsersId500,
>(
  id: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getUsersId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersId>>,
          TError,
          Awaited<ReturnType<typeof getUsersId>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getUsersId>>>,
  TError = GetUsersId401 | GetUsersId403 | GetUsersId404 | GetUsersId500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getUsersId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersId>>,
          TError,
          Awaited<ReturnType<typeof getUsersId>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getUsersId>>>,
  TError = GetUsersId401 | GetUsersId403 | GetUsersId404 | GetUsersId500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getUsersId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get user by id
 */

export function useGetUsersIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getUsersId>>>,
  TError = GetUsersId401 | GetUsersId403 | GetUsersId404 | GetUsersId500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getUsersId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUsersIdInfiniteQueryOptions(id, options);

  const query = useInfiniteQuery(
    queryOptions,
    queryClient
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get user by id
 */
export const useSetGetUsersIdInfiniteQueryData = () => {
  const queryClient = useQueryClient();
  return (
    id: string,
    updater:
      | InfiniteData<Awaited<ReturnType<typeof getUsersId>>>
      | undefined
      | ((
          old: InfiniteData<Awaited<ReturnType<typeof getUsersId>>> | undefined
        ) => InfiniteData<Awaited<ReturnType<typeof getUsersId>>> | undefined)
  ) => {
    queryClient.setQueryData(getGetUsersIdInfiniteQueryKey(id), updater);
  };
};

/**
 * @summary Get user by id
 */
export const useGetGetUsersIdInfiniteQueryData = () => {
  const queryClient = useQueryClient();
  return (id: string) =>
    queryClient.getQueryData<
      InfiniteData<Awaited<ReturnType<typeof getUsersId>>>
    >(getGetUsersIdInfiniteQueryKey(id));
};

export const getGetUsersIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsersId>>,
  TError = GetUsersId401 | GetUsersId403 | GetUsersId404 | GetUsersId500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUsersIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersId>>> = ({
    signal,
  }) => getUsersId(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUsersId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsersId>>
>;
export type GetUsersIdQueryError =
  | GetUsersId401
  | GetUsersId403
  | GetUsersId404
  | GetUsersId500;

export function useGetUsersId<
  TData = Awaited<ReturnType<typeof getUsersId>>,
  TError = GetUsersId401 | GetUsersId403 | GetUsersId404 | GetUsersId500,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersId>>,
          TError,
          Awaited<ReturnType<typeof getUsersId>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersId<
  TData = Awaited<ReturnType<typeof getUsersId>>,
  TError = GetUsersId401 | GetUsersId403 | GetUsersId404 | GetUsersId500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersId>>,
          TError,
          Awaited<ReturnType<typeof getUsersId>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersId<
  TData = Awaited<ReturnType<typeof getUsersId>>,
  TError = GetUsersId401 | GetUsersId403 | GetUsersId404 | GetUsersId500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get user by id
 */

export function useGetUsersId<
  TData = Awaited<ReturnType<typeof getUsersId>>,
  TError = GetUsersId401 | GetUsersId403 | GetUsersId404 | GetUsersId500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUsersIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get user by id
 */
export const useSetGetUsersIdQueryData = () => {
  const queryClient = useQueryClient();
  return (
    id: string,
    updater:
      | Awaited<ReturnType<typeof getUsersId>>
      | undefined
      | ((
          old: Awaited<ReturnType<typeof getUsersId>> | undefined
        ) => Awaited<ReturnType<typeof getUsersId>> | undefined)
  ) => {
    queryClient.setQueryData(getGetUsersIdQueryKey(id), updater);
  };
};

/**
 * @summary Get user by id
 */
export const useGetGetUsersIdQueryData = () => {
  const queryClient = useQueryClient();
  return (id: string) =>
    queryClient.getQueryData<Awaited<ReturnType<typeof getUsersId>>>(
      getGetUsersIdQueryKey(id)
    );
};
