/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiV1UsersId200,
  GetApiV1UsersId404,
  PostApiV1Users201,
  PostApiV1UsersBody
} from '../model';

import { customInstance } from '../../lib/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Create user
 */
export type postApiV1UsersResponse201 = {
  data: PostApiV1Users201
  status: 201
}

export type postApiV1UsersResponseSuccess = (postApiV1UsersResponse201) & {
  headers: Headers;
};
;

export type postApiV1UsersResponse = (postApiV1UsersResponseSuccess)

export const getPostApiV1UsersUrl = () => {




  return `/api/v1/users`
}

export const postApiV1Users = async (postApiV1UsersBody: PostApiV1UsersBody, options?: RequestInit): Promise<postApiV1UsersResponse> => {

  return customInstance<postApiV1UsersResponse>(getPostApiV1UsersUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1UsersBody,)
  }
);}




export const getPostApiV1UsersMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Users>>, TError,{data: PostApiV1UsersBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Users>>, TError,{data: PostApiV1UsersBody}, TContext> => {

const mutationKey = ['postApiV1Users'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Users>>, {data: PostApiV1UsersBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Users(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1UsersMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Users>>>
    export type PostApiV1UsersMutationBody = PostApiV1UsersBody
    export type PostApiV1UsersMutationError = unknown

    /**
 * @summary Create user
 */
export const usePostApiV1Users = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Users>>, TError,{data: PostApiV1UsersBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Users>>,
        TError,
        {data: PostApiV1UsersBody},
        TContext
      > => {
      return useMutation(getPostApiV1UsersMutationOptions(options), queryClient);
    }
    /**
 * @summary Get user by id
 */
export type getApiV1UsersIdResponse200 = {
  data: GetApiV1UsersId200
  status: 200
}

export type getApiV1UsersIdResponse404 = {
  data: GetApiV1UsersId404
  status: 404
}

export type getApiV1UsersIdResponseSuccess = (getApiV1UsersIdResponse200) & {
  headers: Headers;
};
export type getApiV1UsersIdResponseError = (getApiV1UsersIdResponse404) & {
  headers: Headers;
};

export type getApiV1UsersIdResponse = (getApiV1UsersIdResponseSuccess | getApiV1UsersIdResponseError)

export const getGetApiV1UsersIdUrl = (id: string,) => {




  return `/api/v1/users/${id}`
}

export const getApiV1UsersId = async (id: string, options?: RequestInit): Promise<getApiV1UsersIdResponse> => {

  return customInstance<getApiV1UsersIdResponse>(getGetApiV1UsersIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1UsersIdQueryKey = (id: string,) => {
    return [
    `/api/v1/users/${id}`
    ] as const;
    }


export const getGetApiV1UsersIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1UsersId>>, TError = GetApiV1UsersId404>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1UsersIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1UsersId>>> = ({ signal }) => getApiV1UsersId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1UsersIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1UsersId>>>
export type GetApiV1UsersIdQueryError = GetApiV1UsersId404


export function useGetApiV1UsersId<TData = Awaited<ReturnType<typeof getApiV1UsersId>>, TError = GetApiV1UsersId404>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1UsersId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1UsersId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1UsersId<TData = Awaited<ReturnType<typeof getApiV1UsersId>>, TError = GetApiV1UsersId404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1UsersId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1UsersId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1UsersId<TData = Awaited<ReturnType<typeof getApiV1UsersId>>, TError = GetApiV1UsersId404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user by id
 */

export function useGetApiV1UsersId<TData = Awaited<ReturnType<typeof getApiV1UsersId>>, TError = GetApiV1UsersId404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1UsersIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






