/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteQuizIdQuizzesQuestionsQuestionId404Error } from './deleteQuizIdQuizzesQuestionsQuestionId404Error';
import type { DeleteQuizIdQuizzesQuestionsQuestionId404Meta } from './deleteQuizIdQuizzesQuestionsQuestionId404Meta';

export type DeleteQuizIdQuizzesQuestionsQuestionId404 = {
  success: false;
  error: DeleteQuizIdQuizzesQuestionsQuestionId404Error;
  meta?: DeleteQuizIdQuizzesQuestionsQuestionId404Meta;
};
