/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteQuizIdQuizzesQuestionsQuestionId401Error } from './deleteQuizIdQuizzesQuestionsQuestionId401Error';
import type { DeleteQuizIdQuizzesQuestionsQuestionId401Meta } from './deleteQuizIdQuizzesQuestionsQuestionId401Meta';

export type DeleteQuizIdQuizzesQuestionsQuestionId401 = {
  success: false;
  error: DeleteQuizIdQuizzesQuestionsQuestionId401Error;
  meta?: DeleteQuizIdQuizzesQuestionsQuestionId401Meta;
};
