/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteQuizzesQuestionsQuestionId403Error } from './deleteQuizzesQuestionsQuestionId403Error';
import type { DeleteQuizzesQuestionsQuestionId403Meta } from './deleteQuizzesQuestionsQuestionId403Meta';

export type DeleteQuizzesQuestionsQuestionId403 = {
  success: false;
  error: DeleteQuizzesQuestionsQuestionId403Error;
  meta?: DeleteQuizzesQuestionsQuestionId403Meta;
};
