/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteQuizzesQuizId404Error } from './deleteQuizzesQuizId404Error';
import type { DeleteQuizzesQuizId404Meta } from './deleteQuizzesQuizId404Meta';

export type DeleteQuizzesQuizId404 = {
  success: false;
  error: DeleteQuizzesQuizId404Error;
  meta?: DeleteQuizzesQuizId404Meta;
};
