/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteQuizzesQuestionsQuestionIdOptionsOptionId404Error } from './deleteQuizzesQuestionsQuestionIdOptionsOptionId404Error';
import type { DeleteQuizzesQuestionsQuestionIdOptionsOptionId404Meta } from './deleteQuizzesQuestionsQuestionIdOptionsOptionId404Meta';

export type DeleteQuizzesQuestionsQuestionIdOptionsOptionId404 = {
  success: false;
  error: DeleteQuizzesQuestionsQuestionIdOptionsOptionId404Error;
  meta?: DeleteQuizzesQuestionsQuestionIdOptionsOptionId404Meta;
};
