/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteQuizzesQuizId500Error } from './deleteQuizzesQuizId500Error';
import type { DeleteQuizzesQuizId500Meta } from './deleteQuizzesQuizId500Meta';

export type DeleteQuizzesQuizId500 = {
  success: false;
  error: DeleteQuizzesQuizId500Error;
  meta?: DeleteQuizzesQuizId500Meta;
};
