/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteQuizzesQuestionsQuestionId500Error } from './deleteQuizzesQuestionsQuestionId500Error';
import type { DeleteQuizzesQuestionsQuestionId500Meta } from './deleteQuizzesQuestionsQuestionId500Meta';

export type DeleteQuizzesQuestionsQuestionId500 = {
  success: false;
  error: DeleteQuizzesQuestionsQuestionId500Error;
  meta?: DeleteQuizzesQuestionsQuestionId500Meta;
};
