/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteQuizzesQuizId403Error } from './deleteQuizzesQuizId403Error';
import type { DeleteQuizzesQuizId403Meta } from './deleteQuizzesQuizId403Meta';

export type DeleteQuizzesQuizId403 = {
  success: false;
  error: DeleteQuizzesQuizId403Error;
  meta?: DeleteQuizzesQuizId403Meta;
};
