/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteQuizzesQuestionsQuestionId401Error } from './deleteQuizzesQuestionsQuestionId401Error';
import type { DeleteQuizzesQuestionsQuestionId401Meta } from './deleteQuizzesQuestionsQuestionId401Meta';

export type DeleteQuizzesQuestionsQuestionId401 = {
  success: false;
  error: DeleteQuizzesQuestionsQuestionId401Error;
  meta?: DeleteQuizzesQuestionsQuestionId401Meta;
};
