/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteQuizzesQuizId401Error } from './deleteQuizzesQuizId401Error';
import type { DeleteQuizzesQuizId401Meta } from './deleteQuizzesQuizId401Meta';

export type DeleteQuizzesQuizId401 = {
  success: false;
  error: DeleteQuizzesQuizId401Error;
  meta?: DeleteQuizzesQuizId401Meta;
};
