/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteQuizzesOptionsOptionId401Error } from './deleteQuizzesOptionsOptionId401Error';
import type { DeleteQuizzesOptionsOptionId401Meta } from './deleteQuizzesOptionsOptionId401Meta';

export type DeleteQuizzesOptionsOptionId401 = {
  success: false;
  error: DeleteQuizzesOptionsOptionId401Error;
  meta?: DeleteQuizzesOptionsOptionId401Meta;
};
