/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteQuizzesQuestionsQuestionIdOptionsOptionId401Error } from './deleteQuizzesQuestionsQuestionIdOptionsOptionId401Error';
import type { DeleteQuizzesQuestionsQuestionIdOptionsOptionId401Meta } from './deleteQuizzesQuestionsQuestionIdOptionsOptionId401Meta';

export type DeleteQuizzesQuestionsQuestionIdOptionsOptionId401 = {
  success: false;
  error: DeleteQuizzesQuestionsQuestionIdOptionsOptionId401Error;
  meta?: DeleteQuizzesQuestionsQuestionIdOptionsOptionId401Meta;
};
