/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteQuizzesOptionsOptionId403Error } from './deleteQuizzesOptionsOptionId403Error';
import type { DeleteQuizzesOptionsOptionId403Meta } from './deleteQuizzesOptionsOptionId403Meta';

export type DeleteQuizzesOptionsOptionId403 = {
  success: false;
  error: DeleteQuizzesOptionsOptionId403Error;
  meta?: DeleteQuizzesOptionsOptionId403Meta;
};
