/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteQuizzesQuestionsQuestionIdOptionsOptionId403Error } from './deleteQuizzesQuestionsQuestionIdOptionsOptionId403Error';
import type { DeleteQuizzesQuestionsQuestionIdOptionsOptionId403Meta } from './deleteQuizzesQuestionsQuestionIdOptionsOptionId403Meta';

export type DeleteQuizzesQuestionsQuestionIdOptionsOptionId403 = {
  success: false;
  error: DeleteQuizzesQuestionsQuestionIdOptionsOptionId403Error;
  meta?: DeleteQuizzesQuestionsQuestionIdOptionsOptionId403Meta;
};
