/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteQuizzesQuestionsQuestionId404Error } from './deleteQuizzesQuestionsQuestionId404Error';
import type { DeleteQuizzesQuestionsQuestionId404Meta } from './deleteQuizzesQuestionsQuestionId404Meta';

export type DeleteQuizzesQuestionsQuestionId404 = {
  success: false;
  error: DeleteQuizzesQuestionsQuestionId404Error;
  meta?: DeleteQuizzesQuestionsQuestionId404Meta;
};
