/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteQuizzesOptionsOptionId500Error } from './deleteQuizzesOptionsOptionId500Error';
import type { DeleteQuizzesOptionsOptionId500Meta } from './deleteQuizzesOptionsOptionId500Meta';

export type DeleteQuizzesOptionsOptionId500 = {
  success: false;
  error: DeleteQuizzesOptionsOptionId500Error;
  meta?: DeleteQuizzesOptionsOptionId500Meta;
};
