/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteQuizIdQuizzesQuestionsQuestionId403Error } from './deleteQuizIdQuizzesQuestionsQuestionId403Error';
import type { DeleteQuizIdQuizzesQuestionsQuestionId403Meta } from './deleteQuizIdQuizzesQuestionsQuestionId403Meta';

export type DeleteQuizIdQuizzesQuestionsQuestionId403 = {
  success: false;
  error: DeleteQuizIdQuizzesQuestionsQuestionId403Error;
  meta?: DeleteQuizIdQuizzesQuestionsQuestionId403Meta;
};
