/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1QuizzesId404Error } from './getApiV1QuizzesId404Error';
import type { GetApiV1QuizzesId404Meta } from './getApiV1QuizzesId404Meta';

export type GetApiV1QuizzesId404 = {
  success: false;
  error: GetApiV1QuizzesId404Error;
  meta?: GetApiV1QuizzesId404Meta;
};
