/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1SessionsSessionId200Data } from './getApiV1SessionsSessionId200Data';
import type { GetApiV1SessionsSessionId200Meta } from './getApiV1SessionsSessionId200Meta';

export type GetApiV1SessionsSessionId200 = {
  success: true;
  message: string;
  data?: GetApiV1SessionsSessionId200Data;
  meta?: GetApiV1SessionsSessionId200Meta;
};
