/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetAuthMe200Data } from './getAuthMe200Data';
import type { GetAuthMe200Meta } from './getAuthMe200Meta';

export type GetAuthMe200 = {
  success: true;
  message: string;
  data: GetAuthMe200Data;
  meta?: GetAuthMe200Meta;
};
