/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1AuthMe200DataUser } from './getApiV1AuthMe200DataUser';

export type GetApiV1AuthMe200Data = {
  user: GetApiV1AuthMe200DataUser;
};
