/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1Health200Data } from './getApiV1Health200Data';
import type { GetApiV1Health200Meta } from './getApiV1Health200Meta';

export type GetApiV1Health200 = {
  success: true;
  message: string;
  data?: GetApiV1Health200Data;
  meta?: GetApiV1Health200Meta;
};
