/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1AuthMe200Data } from './getApiV1AuthMe200Data';
import type { GetApiV1AuthMe200Meta } from './getApiV1AuthMe200Meta';

export type GetApiV1AuthMe200 = {
  success: true;
  message: string;
  data?: GetApiV1AuthMe200Data;
  meta?: GetApiV1AuthMe200Meta;
};
