/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1Health200DataStatus } from './getApiV1Health200DataStatus';

export type GetApiV1Health200Data = {
  status: GetApiV1Health200DataStatus;
  timestamp: string;
  uptime: number;
  [key: string]: unknown;
 };
