/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1Quizzes200DataItem } from './getApiV1Quizzes200DataItem';
import type { GetApiV1Quizzes200Meta } from './getApiV1Quizzes200Meta';

export type GetApiV1Quizzes200 = {
  success: true;
  message: string;
  data?: GetApiV1Quizzes200DataItem[];
  meta?: GetApiV1Quizzes200Meta;
};
