/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1SessionsSessionId404Error } from './getApiV1SessionsSessionId404Error';
import type { GetApiV1SessionsSessionId404Meta } from './getApiV1SessionsSessionId404Meta';

export type GetApiV1SessionsSessionId404 = {
  success: false;
  error: GetApiV1SessionsSessionId404Error;
  meta?: GetApiV1SessionsSessionId404Meta;
};
