/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1QuizzesId200Data } from './getApiV1QuizzesId200Data';
import type { GetApiV1QuizzesId200Meta } from './getApiV1QuizzesId200Meta';

export type GetApiV1QuizzesId200 = {
  success: true;
  message: string;
  data?: GetApiV1QuizzesId200Data;
  meta?: GetApiV1QuizzesId200Meta;
};
