/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetAuthMe401Error } from './getAuthMe401Error';
import type { GetAuthMe401Meta } from './getAuthMe401Meta';

export type GetAuthMe401 = {
  success: false;
  error: GetAuthMe401Error;
  meta?: GetAuthMe401Meta;
};
