/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1AuthMe401Error } from './getApiV1AuthMe401Error';
import type { GetApiV1AuthMe401Meta } from './getApiV1AuthMe401Meta';

export type GetApiV1AuthMe401 = {
  success: false;
  error: GetApiV1AuthMe401Error;
  meta?: GetApiV1AuthMe401Meta;
};
