/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetHealth200Data } from './getHealth200Data';
import type { GetHealth200Meta } from './getHealth200Meta';

export type GetHealth200 = {
  success: true;
  message: string;
  data: GetHealth200Data;
  meta?: GetHealth200Meta;
};
