/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */

export type GetHealth200DataStatus =
  (typeof GetHealth200DataStatus)[keyof typeof GetHealth200DataStatus];

export const GetHealth200DataStatus = {
  healthy: 'healthy',
} as const;
