/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetHealth200DataStatus } from './getHealth200DataStatus';

export type GetHealth200Data = {
  status: GetHealth200DataStatus;
  timestamp: string;
  uptime: number;
  [key: string]: unknown;
};
