/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuizzesId403Error } from './getQuizzesId403Error';
import type { GetQuizzesId403Meta } from './getQuizzesId403Meta';

export type GetQuizzesId403 = {
  success: false;
  error: GetQuizzesId403Error;
  meta?: GetQuizzesId403Meta;
};
