/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuizzesId500Error } from './getQuizzesId500Error';
import type { GetQuizzesId500Meta } from './getQuizzesId500Meta';

export type GetQuizzesId500 = {
  success: false;
  error: GetQuizzesId500Error;
  meta?: GetQuizzesId500Meta;
};
