/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuizzesAdminId403Error } from './getQuizzesAdminId403Error';
import type { GetQuizzesAdminId403Meta } from './getQuizzesAdminId403Meta';

export type GetQuizzesAdminId403 = {
  success: false;
  error: GetQuizzesAdminId403Error;
  meta?: GetQuizzesAdminId403Meta;
};
