/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuizzes200DataItemQuestionsItem } from './getQuizzes200DataItemQuestionsItem';

export type GetQuizzes200DataItem = {
  id: string;
  title: string;
  /** @nullable */
  description?: string | null;
  isPublished: boolean;
  createdBy: string;
  questions: GetQuizzes200DataItemQuestionsItem[];
};
