/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuizzesAdminId200Data } from './getQuizzesAdminId200Data';
import type { GetQuizzesAdminId200Meta } from './getQuizzesAdminId200Meta';

export type GetQuizzesAdminId200 = {
  success: true;
  message: string;
  data: GetQuizzesAdminId200Data;
  meta?: GetQuizzesAdminId200Meta;
};
