/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuizzes401Error } from './getQuizzes401Error';
import type { GetQuizzes401Meta } from './getQuizzes401Meta';

export type GetQuizzes401 = {
  success: false;
  error: GetQuizzes401Error;
  meta?: GetQuizzes401Meta;
};
