/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuizzesAdminId404Error } from './getQuizzesAdminId404Error';
import type { GetQuizzesAdminId404Meta } from './getQuizzesAdminId404Meta';

export type GetQuizzesAdminId404 = {
  success: false;
  error: GetQuizzesAdminId404Error;
  meta?: GetQuizzesAdminId404Meta;
};
