/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuizzesId404Error } from './getQuizzesId404Error';
import type { GetQuizzesId404Meta } from './getQuizzesId404Meta';

export type GetQuizzesId404 = {
  success: false;
  error: GetQuizzesId404Error;
  meta?: GetQuizzesId404Meta;
};
