/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuizzes403Error } from './getQuizzes403Error';
import type { GetQuizzes403Meta } from './getQuizzes403Meta';

export type GetQuizzes403 = {
  success: false;
  error: GetQuizzes403Error;
  meta?: GetQuizzes403Meta;
};
