/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuizzes200DataItem } from './getQuizzes200DataItem';
import type { GetQuizzes200Meta } from './getQuizzes200Meta';

export type GetQuizzes200 = {
  success: true;
  message: string;
  data: GetQuizzes200DataItem[];
  meta?: GetQuizzes200Meta;
};
