/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuizzesAdminId401Error } from './getQuizzesAdminId401Error';
import type { GetQuizzesAdminId401Meta } from './getQuizzesAdminId401Meta';

export type GetQuizzesAdminId401 = {
  success: false;
  error: GetQuizzesAdminId401Error;
  meta?: GetQuizzesAdminId401Meta;
};
