/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuizzes500Error } from './getQuizzes500Error';
import type { GetQuizzes500Meta } from './getQuizzes500Meta';

export type GetQuizzes500 = {
  success: false;
  error: GetQuizzes500Error;
  meta?: GetQuizzes500Meta;
};
