/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuizzesId401Error } from './getQuizzesId401Error';
import type { GetQuizzesId401Meta } from './getQuizzesId401Meta';

export type GetQuizzesId401 = {
  success: false;
  error: GetQuizzesId401Error;
  meta?: GetQuizzesId401Meta;
};
