/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuizzesAdminId500Error } from './getQuizzesAdminId500Error';
import type { GetQuizzesAdminId500Meta } from './getQuizzesAdminId500Meta';

export type GetQuizzesAdminId500 = {
  success: false;
  error: GetQuizzesAdminId500Error;
  meta?: GetQuizzesAdminId500Meta;
};
