/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuizzesId200Data } from './getQuizzesId200Data';
import type { GetQuizzesId200Meta } from './getQuizzesId200Meta';

export type GetQuizzesId200 = {
  success: true;
  message: string;
  data: GetQuizzesId200Data;
  meta?: GetQuizzesId200Meta;
};
