/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetSessionsSessionId500Error } from './getSessionsSessionId500Error';
import type { GetSessionsSessionId500Meta } from './getSessionsSessionId500Meta';

export type GetSessionsSessionId500 = {
  success: false;
  error: GetSessionsSessionId500Error;
  meta?: GetSessionsSessionId500Meta;
};
