/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetSessionsSessionId403Error } from './getSessionsSessionId403Error';
import type { GetSessionsSessionId403Meta } from './getSessionsSessionId403Meta';

export type GetSessionsSessionId403 = {
  success: false;
  error: GetSessionsSessionId403Error;
  meta?: GetSessionsSessionId403Meta;
};
