/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetSessionsSessionId200Data } from './getSessionsSessionId200Data';
import type { GetSessionsSessionId200Meta } from './getSessionsSessionId200Meta';

export type GetSessionsSessionId200 = {
  success: true;
  message: string;
  data: GetSessionsSessionId200Data;
  meta?: GetSessionsSessionId200Meta;
};
