/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetSessionsSessionId404Error } from './getSessionsSessionId404Error';
import type { GetSessionsSessionId404Meta } from './getSessionsSessionId404Meta';

export type GetSessionsSessionId404 = {
  success: false;
  error: GetSessionsSessionId404Error;
  meta?: GetSessionsSessionId404Meta;
};
