/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetUsersId403Error } from './getUsersId403Error';
import type { GetUsersId403Meta } from './getUsersId403Meta';

export type GetUsersId403 = {
  success: false;
  error: GetUsersId403Error;
  meta?: GetUsersId403Meta;
};
