/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetUsersId200Data } from './getUsersId200Data';
import type { GetUsersId200Meta } from './getUsersId200Meta';

export type GetUsersId200 = {
  success: true;
  message: string;
  data: GetUsersId200Data;
  meta?: GetUsersId200Meta;
};
