/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetUsersId404Error } from './getUsersId404Error';
import type { GetUsersId404Meta } from './getUsersId404Meta';

export type GetUsersId404 = {
  success: false;
  error: GetUsersId404Error;
  meta?: GetUsersId404Meta;
};
