/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetUsersId401Error } from './getUsersId401Error';
import type { GetUsersId401Meta } from './getUsersId401Meta';

export type GetUsersId401 = {
  success: false;
  error: GetUsersId401Error;
  meta?: GetUsersId401Meta;
};
