/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { GetUsersId500Error } from './getUsersId500Error';
import type { GetUsersId500Meta } from './getUsersId500Meta';

export type GetUsersId500 = {
  success: false;
  error: GetUsersId500Error;
  meta?: GetUsersId500Meta;
};
