/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesQuestionsBulk400Error } from './patchQuizzesQuestionsBulk400Error';
import type { PatchQuizzesQuestionsBulk400Meta } from './patchQuizzesQuestionsBulk400Meta';

export type PatchQuizzesQuestionsBulk400 = {
  success: false;
  error: PatchQuizzesQuestionsBulk400Error;
  meta?: PatchQuizzesQuestionsBulk400Meta;
};
