/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesOptionsBulk409Error } from './patchQuizzesOptionsBulk409Error';
import type { PatchQuizzesOptionsBulk409Meta } from './patchQuizzesOptionsBulk409Meta';

export type PatchQuizzesOptionsBulk409 = {
  success: false;
  error: PatchQuizzesOptionsBulk409Error;
  meta?: PatchQuizzesOptionsBulk409Meta;
};
