/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesOptionsBulk401Error } from './patchQuizzesOptionsBulk401Error';
import type { PatchQuizzesOptionsBulk401Meta } from './patchQuizzesOptionsBulk401Meta';

export type PatchQuizzesOptionsBulk401 = {
  success: false;
  error: PatchQuizzesOptionsBulk401Error;
  meta?: PatchQuizzesOptionsBulk401Meta;
};
