/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesOptionsBulk500Error } from './patchQuizzesOptionsBulk500Error';
import type { PatchQuizzesOptionsBulk500Meta } from './patchQuizzesOptionsBulk500Meta';

export type PatchQuizzesOptionsBulk500 = {
  success: false;
  error: PatchQuizzesOptionsBulk500Error;
  meta?: PatchQuizzesOptionsBulk500Meta;
};
