/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesOptionsBulk400Error } from './patchQuizzesOptionsBulk400Error';
import type { PatchQuizzesOptionsBulk400Meta } from './patchQuizzesOptionsBulk400Meta';

export type PatchQuizzesOptionsBulk400 = {
  success: false;
  error: PatchQuizzesOptionsBulk400Error;
  meta?: PatchQuizzesOptionsBulk400Meta;
};
