/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesQuestionsBulk404Error } from './patchQuizzesQuestionsBulk404Error';
import type { PatchQuizzesQuestionsBulk404Meta } from './patchQuizzesQuestionsBulk404Meta';

export type PatchQuizzesQuestionsBulk404 = {
  success: false;
  error: PatchQuizzesQuestionsBulk404Error;
  meta?: PatchQuizzesQuestionsBulk404Meta;
};
