/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesQuizIdQuestionsQuestionIdReorder404Error } from './patchQuizzesQuizIdQuestionsQuestionIdReorder404Error';
import type { PatchQuizzesQuizIdQuestionsQuestionIdReorder404Meta } from './patchQuizzesQuizIdQuestionsQuestionIdReorder404Meta';

export type PatchQuizzesQuizIdQuestionsQuestionIdReorder404 = {
  success: false;
  error: PatchQuizzesQuizIdQuestionsQuestionIdReorder404Error;
  meta?: PatchQuizzesQuizIdQuestionsQuestionIdReorder404Meta;
};
