/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesOptionsBulk404Error } from './patchQuizzesOptionsBulk404Error';
import type { PatchQuizzesOptionsBulk404Meta } from './patchQuizzesOptionsBulk404Meta';

export type PatchQuizzesOptionsBulk404 = {
  success: false;
  error: PatchQuizzesOptionsBulk404Error;
  meta?: PatchQuizzesOptionsBulk404Meta;
};
