/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesQuizIdQuestionsQuestionIdReorder500Error } from './patchQuizzesQuizIdQuestionsQuestionIdReorder500Error';
import type { PatchQuizzesQuizIdQuestionsQuestionIdReorder500Meta } from './patchQuizzesQuizIdQuestionsQuestionIdReorder500Meta';

export type PatchQuizzesQuizIdQuestionsQuestionIdReorder500 = {
  success: false;
  error: PatchQuizzesQuizIdQuestionsQuestionIdReorder500Error;
  meta?: PatchQuizzesQuizIdQuestionsQuestionIdReorder500Meta;
};
