/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesQuizIdQuestionsQuestionIdReorder409Error } from './patchQuizzesQuizIdQuestionsQuestionIdReorder409Error';
import type { PatchQuizzesQuizIdQuestionsQuestionIdReorder409Meta } from './patchQuizzesQuizIdQuestionsQuestionIdReorder409Meta';

export type PatchQuizzesQuizIdQuestionsQuestionIdReorder409 = {
  success: false;
  error: PatchQuizzesQuizIdQuestionsQuestionIdReorder409Error;
  meta?: PatchQuizzesQuizIdQuestionsQuestionIdReorder409Meta;
};
