/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesOptionsOptionId403Error } from './patchQuizzesOptionsOptionId403Error';
import type { PatchQuizzesOptionsOptionId403Meta } from './patchQuizzesOptionsOptionId403Meta';

export type PatchQuizzesOptionsOptionId403 = {
  success: false;
  error: PatchQuizzesOptionsOptionId403Error;
  meta?: PatchQuizzesOptionsOptionId403Meta;
};
