/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesQuizIdQuestionsQuestionIdReorder401Error } from './patchQuizzesQuizIdQuestionsQuestionIdReorder401Error';
import type { PatchQuizzesQuizIdQuestionsQuestionIdReorder401Meta } from './patchQuizzesQuizIdQuestionsQuestionIdReorder401Meta';

export type PatchQuizzesQuizIdQuestionsQuestionIdReorder401 = {
  success: false;
  error: PatchQuizzesQuizIdQuestionsQuestionIdReorder401Error;
  meta?: PatchQuizzesQuizIdQuestionsQuestionIdReorder401Meta;
};
