/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorder200Data } from './patchApiV1QuizzesQuizIdQuestionsQuestionIdReorder200Data';
import type { PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorder200Meta } from './patchApiV1QuizzesQuizIdQuestionsQuestionIdReorder200Meta';

export type PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorder200 = {
  success: true;
  message: string;
  data?: PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorder200Data;
  meta?: PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorder200Meta;
};
