/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesQuestionsQuestionId200Data } from './patchQuizzesQuestionsQuestionId200Data';
import type { PatchQuizzesQuestionsQuestionId200Meta } from './patchQuizzesQuestionsQuestionId200Meta';

export type PatchQuizzesQuestionsQuestionId200 = {
  success: true;
  message: string;
  data: PatchQuizzesQuestionsQuestionId200Data;
  meta?: PatchQuizzesQuestionsQuestionId200Meta;
};
