/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesQuestionsQuestionId401Error } from './patchQuizzesQuestionsQuestionId401Error';
import type { PatchQuizzesQuestionsQuestionId401Meta } from './patchQuizzesQuestionsQuestionId401Meta';

export type PatchQuizzesQuestionsQuestionId401 = {
  success: false;
  error: PatchQuizzesQuestionsQuestionId401Error;
  meta?: PatchQuizzesQuestionsQuestionId401Meta;
};
