/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesQuizIdQuestionsQuestionIdReorder400Error } from './patchQuizzesQuizIdQuestionsQuestionIdReorder400Error';
import type { PatchQuizzesQuizIdQuestionsQuestionIdReorder400Meta } from './patchQuizzesQuizIdQuestionsQuestionIdReorder400Meta';

export type PatchQuizzesQuizIdQuestionsQuestionIdReorder400 = {
  success: false;
  error: PatchQuizzesQuizIdQuestionsQuestionIdReorder400Error;
  meta?: PatchQuizzesQuizIdQuestionsQuestionIdReorder400Meta;
};
