/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesOptionsBulk200DataItem } from './patchQuizzesOptionsBulk200DataItem';
import type { PatchQuizzesOptionsBulk200Meta } from './patchQuizzesOptionsBulk200Meta';

export type PatchQuizzesOptionsBulk200 = {
  success: true;
  message: string;
  data: PatchQuizzesOptionsBulk200DataItem[];
  meta?: PatchQuizzesOptionsBulk200Meta;
};
