/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesQuestionsQuestionId403Error } from './patchQuizzesQuestionsQuestionId403Error';
import type { PatchQuizzesQuestionsQuestionId403Meta } from './patchQuizzesQuestionsQuestionId403Meta';

export type PatchQuizzesQuestionsQuestionId403 = {
  success: false;
  error: PatchQuizzesQuestionsQuestionId403Error;
  meta?: PatchQuizzesQuestionsQuestionId403Meta;
};
