/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesOptionsOptionId404Error } from './patchQuizzesOptionsOptionId404Error';
import type { PatchQuizzesOptionsOptionId404Meta } from './patchQuizzesOptionsOptionId404Meta';

export type PatchQuizzesOptionsOptionId404 = {
  success: false;
  error: PatchQuizzesOptionsOptionId404Error;
  meta?: PatchQuizzesOptionsOptionId404Meta;
};
