/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesQuestionsBulk200DataItem } from './patchQuizzesQuestionsBulk200DataItem';
import type { PatchQuizzesQuestionsBulk200Meta } from './patchQuizzesQuestionsBulk200Meta';

export type PatchQuizzesQuestionsBulk200 = {
  success: true;
  message: string;
  data: PatchQuizzesQuestionsBulk200DataItem[];
  meta?: PatchQuizzesQuestionsBulk200Meta;
};
