/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesQuestionsBulk409Error } from './patchQuizzesQuestionsBulk409Error';
import type { PatchQuizzesQuestionsBulk409Meta } from './patchQuizzesQuestionsBulk409Meta';

export type PatchQuizzesQuestionsBulk409 = {
  success: false;
  error: PatchQuizzesQuestionsBulk409Error;
  meta?: PatchQuizzesQuestionsBulk409Meta;
};
