/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesOptionsBulk403Error } from './patchQuizzesOptionsBulk403Error';
import type { PatchQuizzesOptionsBulk403Meta } from './patchQuizzesOptionsBulk403Meta';

export type PatchQuizzesOptionsBulk403 = {
  success: false;
  error: PatchQuizzesOptionsBulk403Error;
  meta?: PatchQuizzesOptionsBulk403Meta;
};
