/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesQuestionsQuestionId404Error } from './patchQuizzesQuestionsQuestionId404Error';
import type { PatchQuizzesQuestionsQuestionId404Meta } from './patchQuizzesQuestionsQuestionId404Meta';

export type PatchQuizzesQuestionsQuestionId404 = {
  success: false;
  error: PatchQuizzesQuestionsQuestionId404Error;
  meta?: PatchQuizzesQuestionsQuestionId404Meta;
};
