/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesQuestionsBulk500Error } from './patchQuizzesQuestionsBulk500Error';
import type { PatchQuizzesQuestionsBulk500Meta } from './patchQuizzesQuestionsBulk500Meta';

export type PatchQuizzesQuestionsBulk500 = {
  success: false;
  error: PatchQuizzesQuestionsBulk500Error;
  meta?: PatchQuizzesQuestionsBulk500Meta;
};
