/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesQuestionsBulk403Error } from './patchQuizzesQuestionsBulk403Error';
import type { PatchQuizzesQuestionsBulk403Meta } from './patchQuizzesQuestionsBulk403Meta';

export type PatchQuizzesQuestionsBulk403 = {
  success: false;
  error: PatchQuizzesQuestionsBulk403Error;
  meta?: PatchQuizzesQuestionsBulk403Meta;
};
