/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesOptionsOptionId200Data } from './patchQuizzesOptionsOptionId200Data';
import type { PatchQuizzesOptionsOptionId200Meta } from './patchQuizzesOptionsOptionId200Meta';

export type PatchQuizzesOptionsOptionId200 = {
  success: true;
  message: string;
  data: PatchQuizzesOptionsOptionId200Data;
  meta?: PatchQuizzesOptionsOptionId200Meta;
};
