/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiV1QuizzesQuizIdQuestionsQuestionIdReorder200Data = {
  id: string;
  quizId: string;
  questionText: string;
  type: string;
  timeLimit: number;
  points: number;
};
