/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesQuizIdQuestionsQuestionIdReorder200Data } from './patchQuizzesQuizIdQuestionsQuestionIdReorder200Data';
import type { PatchQuizzesQuizIdQuestionsQuestionIdReorder200Meta } from './patchQuizzesQuizIdQuestionsQuestionIdReorder200Meta';

export type PatchQuizzesQuizIdQuestionsQuestionIdReorder200 = {
  success: true;
  message: string;
  data: PatchQuizzesQuizIdQuestionsQuestionIdReorder200Data;
  meta?: PatchQuizzesQuizIdQuestionsQuestionIdReorder200Meta;
};
