/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesOptionsOptionId401Error } from './patchQuizzesOptionsOptionId401Error';
import type { PatchQuizzesOptionsOptionId401Meta } from './patchQuizzesOptionsOptionId401Meta';

export type PatchQuizzesOptionsOptionId401 = {
  success: false;
  error: PatchQuizzesOptionsOptionId401Error;
  meta?: PatchQuizzesOptionsOptionId401Meta;
};
