/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PatchQuizzesQuestionsBulk401Error } from './patchQuizzesQuestionsBulk401Error';
import type { PatchQuizzesQuestionsBulk401Meta } from './patchQuizzesQuestionsBulk401Meta';

export type PatchQuizzesQuestionsBulk401 = {
  success: false;
  error: PatchQuizzesQuestionsBulk401Error;
  meta?: PatchQuizzesQuestionsBulk401Meta;
};
