/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuizIdPublish500Error } from './postQuizzesQuizIdPublish500Error';
import type { PostQuizzesQuizIdPublish500Meta } from './postQuizzesQuizIdPublish500Meta';

export type PostQuizzesQuizIdPublish500 = {
  success: false;
  error: PostQuizzesQuizIdPublish500Error;
  meta?: PostQuizzesQuizIdPublish500Meta;
};
