/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuestionsQuestionIdOptions404Error } from './postQuizzesQuestionsQuestionIdOptions404Error';
import type { PostQuizzesQuestionsQuestionIdOptions404Meta } from './postQuizzesQuestionsQuestionIdOptions404Meta';

export type PostQuizzesQuestionsQuestionIdOptions404 = {
  success: false;
  error: PostQuizzesQuestionsQuestionIdOptions404Error;
  meta?: PostQuizzesQuestionsQuestionIdOptions404Meta;
};
