/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1QuizzesQuizIdQuestions401Error } from './postApiV1QuizzesQuizIdQuestions401Error';
import type { PostApiV1QuizzesQuizIdQuestions401Meta } from './postApiV1QuizzesQuizIdQuestions401Meta';

export type PostApiV1QuizzesQuizIdQuestions401 = {
  success: false;
  error: PostApiV1QuizzesQuizIdQuestions401Error;
  meta?: PostApiV1QuizzesQuizIdQuestions401Meta;
};
