/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostSessionsJoin400Error } from './postSessionsJoin400Error';
import type { PostSessionsJoin400Meta } from './postSessionsJoin400Meta';

export type PostSessionsJoin400 = {
  success: false;
  error: PostSessionsJoin400Error;
  meta?: PostSessionsJoin400Meta;
};
