/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuestionsQuestionIdOptions201DataItem } from './postQuizzesQuestionsQuestionIdOptions201DataItem';
import type { PostQuizzesQuestionsQuestionIdOptions201Meta } from './postQuizzesQuestionsQuestionIdOptions201Meta';

export type PostQuizzesQuestionsQuestionIdOptions201 = {
  success: true;
  message: string;
  data: PostQuizzesQuestionsQuestionIdOptions201DataItem[];
  meta?: PostQuizzesQuestionsQuestionIdOptions201Meta;
};
