/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuizIdQuestions404Error } from './postQuizzesQuizIdQuestions404Error';
import type { PostQuizzesQuizIdQuestions404Meta } from './postQuizzesQuizIdQuestions404Meta';

export type PostQuizzesQuizIdQuestions404 = {
  success: false;
  error: PostQuizzesQuizIdQuestions404Error;
  meta?: PostQuizzesQuizIdQuestions404Meta;
};
