/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostSessions403Error } from './postSessions403Error';
import type { PostSessions403Meta } from './postSessions403Meta';

export type PostSessions403 = {
  success: false;
  error: PostSessions403Error;
  meta?: PostSessions403Meta;
};
