/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzes400Error } from './postQuizzes400Error';
import type { PostQuizzes400Meta } from './postQuizzes400Meta';

export type PostQuizzes400 = {
  success: false;
  error: PostQuizzes400Error;
  meta?: PostQuizzes400Meta;
};
