/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1AuthLogin401Error } from './postApiV1AuthLogin401Error';
import type { PostApiV1AuthLogin401Meta } from './postApiV1AuthLogin401Meta';

export type PostApiV1AuthLogin401 = {
  success: false;
  error: PostApiV1AuthLogin401Error;
  meta?: PostApiV1AuthLogin401Meta;
};
