/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostUsers201DataUser } from './postUsers201DataUser';

export type PostUsers201Data = {
  user: PostUsers201DataUser;
};
