/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuizIdPublish404Error } from './postQuizzesQuizIdPublish404Error';
import type { PostQuizzesQuizIdPublish404Meta } from './postQuizzesQuizIdPublish404Meta';

export type PostQuizzesQuizIdPublish404 = {
  success: false;
  error: PostQuizzesQuizIdPublish404Error;
  meta?: PostQuizzesQuizIdPublish404Meta;
};
