/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuizIdQuestions400Error } from './postQuizzesQuizIdQuestions400Error';
import type { PostQuizzesQuizIdQuestions400Meta } from './postQuizzesQuizIdQuestions400Meta';

export type PostQuizzesQuizIdQuestions400 = {
  success: false;
  error: PostQuizzesQuizIdQuestions400Error;
  meta?: PostQuizzesQuizIdQuestions400Meta;
};
