/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuizIdQuestions403Error } from './postQuizzesQuizIdQuestions403Error';
import type { PostQuizzesQuizIdQuestions403Meta } from './postQuizzesQuizIdQuestions403Meta';

export type PostQuizzesQuizIdQuestions403 = {
  success: false;
  error: PostQuizzesQuizIdQuestions403Error;
  meta?: PostQuizzesQuizIdQuestions403Meta;
};
