/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostSessionsJoin403Error } from './postSessionsJoin403Error';
import type { PostSessionsJoin403Meta } from './postSessionsJoin403Meta';

export type PostSessionsJoin403 = {
  success: false;
  error: PostSessionsJoin403Error;
  meta?: PostSessionsJoin403Meta;
};
