/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostSessionsJoin401Error } from './postSessionsJoin401Error';
import type { PostSessionsJoin401Meta } from './postSessionsJoin401Meta';

export type PostSessionsJoin401 = {
  success: false;
  error: PostSessionsJoin401Error;
  meta?: PostSessionsJoin401Meta;
};
