/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostSessionsSessionIdStart400Error } from './postSessionsSessionIdStart400Error';
import type { PostSessionsSessionIdStart400Meta } from './postSessionsSessionIdStart400Meta';

export type PostSessionsSessionIdStart400 = {
  success: false;
  error: PostSessionsSessionIdStart400Error;
  meta?: PostSessionsSessionIdStart400Meta;
};
