/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostSessionsSessionIdStart404Error } from './postSessionsSessionIdStart404Error';
import type { PostSessionsSessionIdStart404Meta } from './postSessionsSessionIdStart404Meta';

export type PostSessionsSessionIdStart404 = {
  success: false;
  error: PostSessionsSessionIdStart404Error;
  meta?: PostSessionsSessionIdStart404Meta;
};
