/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuestionsQuestionIdOptions400Error } from './postQuizzesQuestionsQuestionIdOptions400Error';
import type { PostQuizzesQuestionsQuestionIdOptions400Meta } from './postQuizzesQuestionsQuestionIdOptions400Meta';

export type PostQuizzesQuestionsQuestionIdOptions400 = {
  success: false;
  error: PostQuizzesQuestionsQuestionIdOptions400Error;
  meta?: PostQuizzesQuestionsQuestionIdOptions400Meta;
};
