/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthRegister201Data } from './postAuthRegister201Data';
import type { PostAuthRegister201Meta } from './postAuthRegister201Meta';

export type PostAuthRegister201 = {
  success: true;
  message: string;
  data: PostAuthRegister201Data;
  meta?: PostAuthRegister201Meta;
};
