/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthLogin200Data } from './postAuthLogin200Data';
import type { PostAuthLogin200Meta } from './postAuthLogin200Meta';

export type PostAuthLogin200 = {
  success: true;
  message: string;
  data: PostAuthLogin200Data;
  meta?: PostAuthLogin200Meta;
};
