/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */

export type PostSessionsJoinBody = {
  /** @minLength 1 */
  joinCode?: string;
  /**
   * @minLength 1
   * @maxLength 30
   */
  nickname?: string;
};
