/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostUsers409Error } from './postUsers409Error';
import type { PostUsers409Meta } from './postUsers409Meta';

export type PostUsers409 = {
  success: false;
  error: PostUsers409Error;
  meta?: PostUsers409Meta;
};
