/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthLogin401Error } from './postAuthLogin401Error';
import type { PostAuthLogin401Meta } from './postAuthLogin401Meta';

export type PostAuthLogin401 = {
  success: false;
  error: PostAuthLogin401Error;
  meta?: PostAuthLogin401Meta;
};
