/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuestionsQuestionIdOptions403Error } from './postQuizzesQuestionsQuestionIdOptions403Error';
import type { PostQuizzesQuestionsQuestionIdOptions403Meta } from './postQuizzesQuestionsQuestionIdOptions403Meta';

export type PostQuizzesQuestionsQuestionIdOptions403 = {
  success: false;
  error: PostQuizzesQuestionsQuestionIdOptions403Error;
  meta?: PostQuizzesQuestionsQuestionIdOptions403Meta;
};
