/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuizIdQuestions500Error } from './postQuizzesQuizIdQuestions500Error';
import type { PostQuizzesQuizIdQuestions500Meta } from './postQuizzesQuizIdQuestions500Meta';

export type PostQuizzesQuizIdQuestions500 = {
  success: false;
  error: PostQuizzesQuizIdQuestions500Error;
  meta?: PostQuizzesQuizIdQuestions500Meta;
};
