/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostSessionsSessionIdStart401Error } from './postSessionsSessionIdStart401Error';
import type { PostSessionsSessionIdStart401Meta } from './postSessionsSessionIdStart401Meta';

export type PostSessionsSessionIdStart401 = {
  success: false;
  error: PostSessionsSessionIdStart401Error;
  meta?: PostSessionsSessionIdStart401Meta;
};
