/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuizIdPublish401Error } from './postQuizzesQuizIdPublish401Error';
import type { PostQuizzesQuizIdPublish401Meta } from './postQuizzesQuizIdPublish401Meta';

export type PostQuizzesQuizIdPublish401 = {
  success: false;
  error: PostQuizzesQuizIdPublish401Error;
  meta?: PostQuizzesQuizIdPublish401Meta;
};
