/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostSessionsJoin500Error } from './postSessionsJoin500Error';
import type { PostSessionsJoin500Meta } from './postSessionsJoin500Meta';

export type PostSessionsJoin500 = {
  success: false;
  error: PostSessionsJoin500Error;
  meta?: PostSessionsJoin500Meta;
};
