/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostSessions401Error } from './postSessions401Error';
import type { PostSessions401Meta } from './postSessions401Meta';

export type PostSessions401 = {
  success: false;
  error: PostSessions401Error;
  meta?: PostSessions401Meta;
};
