/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostSessions201Data } from './postSessions201Data';
import type { PostSessions201Meta } from './postSessions201Meta';

export type PostSessions201 = {
  success: true;
  message: string;
  data: PostSessions201Data;
  meta?: PostSessions201Meta;
};
