/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuizIdPublish200DataQuestionsItemOptionsItem } from './postQuizzesQuizIdPublish200DataQuestionsItemOptionsItem';

export type PostQuizzesQuizIdPublish200DataQuestionsItem = {
  id: string;
  quizId: string;
  questionText: string;
  type: string;
  timeLimit: number;
  points: number;
  order: string;
  options: PostQuizzesQuizIdPublish200DataQuestionsItemOptionsItem[];
};
