/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostSessionsSessionIdStart403Error } from './postSessionsSessionIdStart403Error';
import type { PostSessionsSessionIdStart403Meta } from './postSessionsSessionIdStart403Meta';

export type PostSessionsSessionIdStart403 = {
  success: false;
  error: PostSessionsSessionIdStart403Error;
  meta?: PostSessionsSessionIdStart403Meta;
};
