/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzes403Error } from './postQuizzes403Error';
import type { PostQuizzes403Meta } from './postQuizzes403Meta';

export type PostQuizzes403 = {
  success: false;
  error: PostQuizzes403Error;
  meta?: PostQuizzes403Meta;
};
