/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuizIdQuestions201Data } from './postQuizzesQuizIdQuestions201Data';
import type { PostQuizzesQuizIdQuestions201Meta } from './postQuizzesQuizIdQuestions201Meta';

export type PostQuizzesQuizIdQuestions201 = {
  success: true;
  message: string;
  data: PostQuizzesQuizIdQuestions201Data;
  meta?: PostQuizzesQuizIdQuestions201Meta;
};
