/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostSessionsJoin201Meta } from './postSessionsJoin201Meta';

export type PostSessionsJoin201 = {
  success: true;
  message: string;
  data?: unknown | null;
  meta?: PostSessionsJoin201Meta;
};
