/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1Sessions201Data } from './postApiV1Sessions201Data';
import type { PostApiV1Sessions201Meta } from './postApiV1Sessions201Meta';

export type PostApiV1Sessions201 = {
  success: true;
  message: string;
  data?: PostApiV1Sessions201Data;
  meta?: PostApiV1Sessions201Meta;
};
