/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostUsers400Error } from './postUsers400Error';
import type { PostUsers400Meta } from './postUsers400Meta';

export type PostUsers400 = {
  success: false;
  error: PostUsers400Error;
  meta?: PostUsers400Meta;
};
