/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1AuthRegister409Error } from './postApiV1AuthRegister409Error';
import type { PostApiV1AuthRegister409Meta } from './postApiV1AuthRegister409Meta';

export type PostApiV1AuthRegister409 = {
  success: false;
  error: PostApiV1AuthRegister409Error;
  meta?: PostApiV1AuthRegister409Meta;
};
