/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzes500Error } from './postQuizzes500Error';
import type { PostQuizzes500Meta } from './postQuizzes500Meta';

export type PostQuizzes500 = {
  success: false;
  error: PostQuizzes500Error;
  meta?: PostQuizzes500Meta;
};
