/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostUsers500Error } from './postUsers500Error';
import type { PostUsers500Meta } from './postUsers500Meta';

export type PostUsers500 = {
  success: false;
  error: PostUsers500Error;
  meta?: PostUsers500Meta;
};
