/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV1QuizzesQuizIdQuestionsBody = {
  /** @minLength 1 */
  questionText?: string;
  type?: string;
  /** @minimum 0 */
  timeLimit?: number;
  /** @minimum 0 */
  points?: number;
  /** @pattern ^[a-z]+$ */
  prevOrder?: string;
  /** @pattern ^[a-z]+$ */
  nextOrder?: string;
};
