/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostSessions400Error } from './postSessions400Error';
import type { PostSessions400Meta } from './postSessions400Meta';

export type PostSessions400 = {
  success: false;
  error: PostSessions400Error;
  meta?: PostSessions400Meta;
};
