/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostSessionsSessionIdStart500Error } from './postSessionsSessionIdStart500Error';
import type { PostSessionsSessionIdStart500Meta } from './postSessionsSessionIdStart500Meta';

export type PostSessionsSessionIdStart500 = {
  success: false;
  error: PostSessionsSessionIdStart500Error;
  meta?: PostSessionsSessionIdStart500Meta;
};
