/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuizIdPublish409Error } from './postQuizzesQuizIdPublish409Error';
import type { PostQuizzesQuizIdPublish409Meta } from './postQuizzesQuizIdPublish409Meta';

export type PostQuizzesQuizIdPublish409 = {
  success: false;
  error: PostQuizzesQuizIdPublish409Error;
  meta?: PostQuizzesQuizIdPublish409Meta;
};
