/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuestionsQuestionIdOptions500Error } from './postQuizzesQuestionsQuestionIdOptions500Error';
import type { PostQuizzesQuestionsQuestionIdOptions500Meta } from './postQuizzesQuestionsQuestionIdOptions500Meta';

export type PostQuizzesQuestionsQuestionIdOptions500 = {
  success: false;
  error: PostQuizzesQuestionsQuestionIdOptions500Error;
  meta?: PostQuizzesQuestionsQuestionIdOptions500Meta;
};
