/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1AuthLogin200DataUser } from './postApiV1AuthLogin200DataUser';

export type PostApiV1AuthLogin200Data = {
  user: PostApiV1AuthLogin200DataUser;
};
