/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostSessionsSessionIdStart200Data } from './postSessionsSessionIdStart200Data';
import type { PostSessionsSessionIdStart200Meta } from './postSessionsSessionIdStart200Meta';

export type PostSessionsSessionIdStart200 = {
  success: true;
  message: string;
  data: PostSessionsSessionIdStart200Data;
  meta?: PostSessionsSessionIdStart200Meta;
};
