/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1Quizzes401Error } from './postApiV1Quizzes401Error';
import type { PostApiV1Quizzes401Meta } from './postApiV1Quizzes401Meta';

export type PostApiV1Quizzes401 = {
  success: false;
  error: PostApiV1Quizzes401Error;
  meta?: PostApiV1Quizzes401Meta;
};
