/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuestionsQuestionIdOptions409Error } from './postQuizzesQuestionsQuestionIdOptions409Error';
import type { PostQuizzesQuestionsQuestionIdOptions409Meta } from './postQuizzesQuestionsQuestionIdOptions409Meta';

export type PostQuizzesQuestionsQuestionIdOptions409 = {
  success: false;
  error: PostQuizzesQuestionsQuestionIdOptions409Error;
  meta?: PostQuizzesQuestionsQuestionIdOptions409Meta;
};
