/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostUsers201Data } from './postUsers201Data';
import type { PostUsers201Meta } from './postUsers201Meta';

export type PostUsers201 = {
  success: true;
  message: string;
  data: PostUsers201Data;
  meta?: PostUsers201Meta;
};
