/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzes201Data } from './postQuizzes201Data';
import type { PostQuizzes201Meta } from './postQuizzes201Meta';

export type PostQuizzes201 = {
  success: true;
  message: string;
  data: PostQuizzes201Data;
  meta?: PostQuizzes201Meta;
};
