/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuizIdQuestions409Error } from './postQuizzesQuizIdQuestions409Error';
import type { PostQuizzesQuizIdQuestions409Meta } from './postQuizzesQuizIdQuestions409Meta';

export type PostQuizzesQuizIdQuestions409 = {
  success: false;
  error: PostQuizzesQuizIdQuestions409Error;
  meta?: PostQuizzesQuizIdQuestions409Meta;
};
