/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzes401Error } from './postQuizzes401Error';
import type { PostQuizzes401Meta } from './postQuizzes401Meta';

export type PostQuizzes401 = {
  success: false;
  error: PostQuizzes401Error;
  meta?: PostQuizzes401Meta;
};
