/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1AuthRegister201Data } from './postApiV1AuthRegister201Data';
import type { PostApiV1AuthRegister201Meta } from './postApiV1AuthRegister201Meta';

export type PostApiV1AuthRegister201 = {
  success: true;
  message: string;
  data?: PostApiV1AuthRegister201Data;
  meta?: PostApiV1AuthRegister201Meta;
};
