/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuizIdQuestions401Error } from './postQuizzesQuizIdQuestions401Error';
import type { PostQuizzesQuizIdQuestions401Meta } from './postQuizzesQuizIdQuestions401Meta';

export type PostQuizzesQuizIdQuestions401 = {
  success: false;
  error: PostQuizzesQuizIdQuestions401Error;
  meta?: PostQuizzesQuizIdQuestions401Meta;
};
