/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuizIdPublish200Data } from './postQuizzesQuizIdPublish200Data';
import type { PostQuizzesQuizIdPublish200Meta } from './postQuizzesQuizIdPublish200Meta';

export type PostQuizzesQuizIdPublish200 = {
  success: true;
  message: string;
  data: PostQuizzesQuizIdPublish200Data;
  meta?: PostQuizzesQuizIdPublish200Meta;
};
