/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1QuizzesQuizIdQuestions201Data } from './postApiV1QuizzesQuizIdQuestions201Data';
import type { PostApiV1QuizzesQuizIdQuestions201Meta } from './postApiV1QuizzesQuizIdQuestions201Meta';

export type PostApiV1QuizzesQuizIdQuestions201 = {
  success: true;
  message: string;
  data?: PostApiV1QuizzesQuizIdQuestions201Data;
  meta?: PostApiV1QuizzesQuizIdQuestions201Meta;
};
