/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1AuthLogin200Data } from './postApiV1AuthLogin200Data';
import type { PostApiV1AuthLogin200Meta } from './postApiV1AuthLogin200Meta';

export type PostApiV1AuthLogin200 = {
  success: true;
  message: string;
  data?: PostApiV1AuthLogin200Data;
  meta?: PostApiV1AuthLogin200Meta;
};
