/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzes409Error } from './postQuizzes409Error';
import type { PostQuizzes409Meta } from './postQuizzes409Meta';

export type PostQuizzes409 = {
  success: false;
  error: PostQuizzes409Error;
  meta?: PostQuizzes409Meta;
};
