/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuestionsQuestionIdOptions401Error } from './postQuizzesQuestionsQuestionIdOptions401Error';
import type { PostQuizzesQuestionsQuestionIdOptions401Meta } from './postQuizzesQuestionsQuestionIdOptions401Meta';

export type PostQuizzesQuestionsQuestionIdOptions401 = {
  success: false;
  error: PostQuizzesQuestionsQuestionIdOptions401Error;
  meta?: PostQuizzesQuestionsQuestionIdOptions401Meta;
};
