/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuizIdPublish400Error } from './postQuizzesQuizIdPublish400Error';
import type { PostQuizzesQuizIdPublish400Meta } from './postQuizzesQuizIdPublish400Meta';

export type PostQuizzesQuizIdPublish400 = {
  success: false;
  error: PostQuizzesQuizIdPublish400Error;
  meta?: PostQuizzesQuizIdPublish400Meta;
};
