/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuizzesQuizIdPublish403Error } from './postQuizzesQuizIdPublish403Error';
import type { PostQuizzesQuizIdPublish403Meta } from './postQuizzesQuizIdPublish403Meta';

export type PostQuizzesQuizIdPublish403 = {
  success: false;
  error: PostQuizzesQuizIdPublish403Error;
  meta?: PostQuizzesQuizIdPublish403Meta;
};
