/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1Quizzes201Data } from './postApiV1Quizzes201Data';
import type { PostApiV1Quizzes201Meta } from './postApiV1Quizzes201Meta';

export type PostApiV1Quizzes201 = {
  success: true;
  message: string;
  data?: PostApiV1Quizzes201Data;
  meta?: PostApiV1Quizzes201Meta;
};
