/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthRegister409Error } from './postAuthRegister409Error';
import type { PostAuthRegister409Meta } from './postAuthRegister409Meta';

export type PostAuthRegister409 = {
  success: false;
  error: PostAuthRegister409Error;
  meta?: PostAuthRegister409Meta;
};
