/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1SessionsSessionIdStart200Data } from './postApiV1SessionsSessionIdStart200Data';
import type { PostApiV1SessionsSessionIdStart200Meta } from './postApiV1SessionsSessionIdStart200Meta';

export type PostApiV1SessionsSessionIdStart200 = {
  success: true;
  message: string;
  data?: PostApiV1SessionsSessionIdStart200Data;
  meta?: PostApiV1SessionsSessionIdStart200Meta;
};
