/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Live Quiz Arena API
 * Versioned backend contract for auth, user, quiz, and session
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiV1SessionsSessionId200,
  GetApiV1SessionsSessionId404,
  PostApiV1Sessions201,
  PostApiV1SessionsBody,
  PostApiV1SessionsJoin201,
  PostApiV1SessionsJoinBody,
  PostApiV1SessionsSessionIdStart200
} from '../model';

import { customInstance } from '../../lib/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Create a live session
 */
export type postApiV1SessionsResponse201 = {
  data: PostApiV1Sessions201
  status: 201
}

export type postApiV1SessionsResponseSuccess = (postApiV1SessionsResponse201) & {
  headers: Headers;
};
;

export type postApiV1SessionsResponse = (postApiV1SessionsResponseSuccess)

export const getPostApiV1SessionsUrl = () => {




  return `/api/v1/sessions`
}

export const postApiV1Sessions = async (postApiV1SessionsBody: PostApiV1SessionsBody, options?: RequestInit): Promise<postApiV1SessionsResponse> => {

  return customInstance<postApiV1SessionsResponse>(getPostApiV1SessionsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1SessionsBody,)
  }
);}




export const getPostApiV1SessionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Sessions>>, TError,{data: PostApiV1SessionsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Sessions>>, TError,{data: PostApiV1SessionsBody}, TContext> => {

const mutationKey = ['postApiV1Sessions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Sessions>>, {data: PostApiV1SessionsBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Sessions(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SessionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Sessions>>>
    export type PostApiV1SessionsMutationBody = PostApiV1SessionsBody
    export type PostApiV1SessionsMutationError = unknown

    /**
 * @summary Create a live session
 */
export const usePostApiV1Sessions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Sessions>>, TError,{data: PostApiV1SessionsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Sessions>>,
        TError,
        {data: PostApiV1SessionsBody},
        TContext
      > => {
      return useMutation(getPostApiV1SessionsMutationOptions(options), queryClient);
    }
    /**
 * @summary Get session by id
 */
export type getApiV1SessionsSessionIdResponse200 = {
  data: GetApiV1SessionsSessionId200
  status: 200
}

export type getApiV1SessionsSessionIdResponse404 = {
  data: GetApiV1SessionsSessionId404
  status: 404
}

export type getApiV1SessionsSessionIdResponseSuccess = (getApiV1SessionsSessionIdResponse200) & {
  headers: Headers;
};
export type getApiV1SessionsSessionIdResponseError = (getApiV1SessionsSessionIdResponse404) & {
  headers: Headers;
};

export type getApiV1SessionsSessionIdResponse = (getApiV1SessionsSessionIdResponseSuccess | getApiV1SessionsSessionIdResponseError)

export const getGetApiV1SessionsSessionIdUrl = (sessionId: string,) => {




  return `/api/v1/sessions/${sessionId}`
}

export const getApiV1SessionsSessionId = async (sessionId: string, options?: RequestInit): Promise<getApiV1SessionsSessionIdResponse> => {

  return customInstance<getApiV1SessionsSessionIdResponse>(getGetApiV1SessionsSessionIdUrl(sessionId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SessionsSessionIdQueryKey = (sessionId: string,) => {
    return [
    `/api/v1/sessions/${sessionId}`
    ] as const;
    }


export const getGetApiV1SessionsSessionIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SessionsSessionId>>, TError = GetApiV1SessionsSessionId404>(sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SessionsSessionId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SessionsSessionIdQueryKey(sessionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SessionsSessionId>>> = ({ signal }) => getApiV1SessionsSessionId(sessionId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(sessionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SessionsSessionId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SessionsSessionIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SessionsSessionId>>>
export type GetApiV1SessionsSessionIdQueryError = GetApiV1SessionsSessionId404


export function useGetApiV1SessionsSessionId<TData = Awaited<ReturnType<typeof getApiV1SessionsSessionId>>, TError = GetApiV1SessionsSessionId404>(
 sessionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SessionsSessionId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SessionsSessionId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SessionsSessionId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SessionsSessionId<TData = Awaited<ReturnType<typeof getApiV1SessionsSessionId>>, TError = GetApiV1SessionsSessionId404>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SessionsSessionId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SessionsSessionId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SessionsSessionId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SessionsSessionId<TData = Awaited<ReturnType<typeof getApiV1SessionsSessionId>>, TError = GetApiV1SessionsSessionId404>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SessionsSessionId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get session by id
 */

export function useGetApiV1SessionsSessionId<TData = Awaited<ReturnType<typeof getApiV1SessionsSessionId>>, TError = GetApiV1SessionsSessionId404>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SessionsSessionId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SessionsSessionIdQueryOptions(sessionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Join a session by join code
 */
export type postApiV1SessionsJoinResponse201 = {
  data: PostApiV1SessionsJoin201
  status: 201
}

export type postApiV1SessionsJoinResponseSuccess = (postApiV1SessionsJoinResponse201) & {
  headers: Headers;
};
;

export type postApiV1SessionsJoinResponse = (postApiV1SessionsJoinResponseSuccess)

export const getPostApiV1SessionsJoinUrl = () => {




  return `/api/v1/sessions/join`
}

export const postApiV1SessionsJoin = async (postApiV1SessionsJoinBody: PostApiV1SessionsJoinBody, options?: RequestInit): Promise<postApiV1SessionsJoinResponse> => {

  return customInstance<postApiV1SessionsJoinResponse>(getPostApiV1SessionsJoinUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1SessionsJoinBody,)
  }
);}




export const getPostApiV1SessionsJoinMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SessionsJoin>>, TError,{data: PostApiV1SessionsJoinBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SessionsJoin>>, TError,{data: PostApiV1SessionsJoinBody}, TContext> => {

const mutationKey = ['postApiV1SessionsJoin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SessionsJoin>>, {data: PostApiV1SessionsJoinBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1SessionsJoin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SessionsJoinMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SessionsJoin>>>
    export type PostApiV1SessionsJoinMutationBody = PostApiV1SessionsJoinBody
    export type PostApiV1SessionsJoinMutationError = unknown

    /**
 * @summary Join a session by join code
 */
export const usePostApiV1SessionsJoin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SessionsJoin>>, TError,{data: PostApiV1SessionsJoinBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SessionsJoin>>,
        TError,
        {data: PostApiV1SessionsJoinBody},
        TContext
      > => {
      return useMutation(getPostApiV1SessionsJoinMutationOptions(options), queryClient);
    }
    /**
 * @summary Start session
 */
export type postApiV1SessionsSessionIdStartResponse200 = {
  data: PostApiV1SessionsSessionIdStart200
  status: 200
}

export type postApiV1SessionsSessionIdStartResponseSuccess = (postApiV1SessionsSessionIdStartResponse200) & {
  headers: Headers;
};
;

export type postApiV1SessionsSessionIdStartResponse = (postApiV1SessionsSessionIdStartResponseSuccess)

export const getPostApiV1SessionsSessionIdStartUrl = (sessionId: string,) => {




  return `/api/v1/sessions/${sessionId}/start`
}

export const postApiV1SessionsSessionIdStart = async (sessionId: string, options?: RequestInit): Promise<postApiV1SessionsSessionIdStartResponse> => {

  return customInstance<postApiV1SessionsSessionIdStartResponse>(getPostApiV1SessionsSessionIdStartUrl(sessionId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiV1SessionsSessionIdStartMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SessionsSessionIdStart>>, TError,{sessionId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SessionsSessionIdStart>>, TError,{sessionId: string}, TContext> => {

const mutationKey = ['postApiV1SessionsSessionIdStart'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SessionsSessionIdStart>>, {sessionId: string}> = (props) => {
          const {sessionId} = props ?? {};

          return  postApiV1SessionsSessionIdStart(sessionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SessionsSessionIdStartMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SessionsSessionIdStart>>>

    export type PostApiV1SessionsSessionIdStartMutationError = unknown

    /**
 * @summary Start session
 */
export const usePostApiV1SessionsSessionIdStart = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SessionsSessionIdStart>>, TError,{sessionId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SessionsSessionIdStart>>,
        TError,
        {sessionId: string},
        TContext
      > => {
      return useMutation(getPostApiV1SessionsSessionIdStartMutationOptions(options), queryClient);
    }
